import type { Kysely, Transaction } from 'kysely';
import type { DB } from './generated.ts';

// Hand-written database type surface. This file holds only the aliases that
// cannot be derived from the schema.
//
// Import boundary:
//   - `generated.ts` — the schema. `DB` and the per-table interfaces. Machine-
//     owned, regenerated by `repel db codegen` on every migration up/down/nuke.
//   - `types.ts` (this file) — the hand-written `Db` / `Tx` aliases.
// `DB` is intentionally NOT re-exported here, so each symbol has exactly one
// import path.
//
// Column keys in the generated interfaces are camelCase; Kysely's
// CamelCasePlugin (configured in `client.ts`) rewrites both column and table
// identifiers to snake_case in the emitted SQL — `selectFrom('contactHandle')`
// produces `from "contact_handle"`. The generator runs with `--camel-case` to
// match the plugin.

// A Kysely instance bound to DB, or a transaction against it.
// `Tx` is the strict service-layer type: every feature operation runs inside
// a transaction, and the `runInTx` / `runInOrgTx` decorators in `tx.ts` close
// over it. Flows and views take a `Tx` as their first argument.
export type Db = Kysely<DB>;
export type Tx = Transaction<DB>;
