import type { Prisma, PrismaClient } from './prisma/client';

// Hand-written database type surface. This file holds only the aliases that
// cannot be derived from the schema.
//
// Import boundary:
//   - `src/prisma/` — the generated client. `PrismaClient`, the `Prisma`
//     namespace, model and input types. Machine-owned, regenerated by
//     `repel db codegen` (prisma generate).
//   - `types.ts` (this file) — the hand-written `Db` / `Tx` aliases and the
//     JSON value aliases.

// A Prisma client bound to the schema, or a transaction against it.
// `Tx` is the strict service-layer type: every feature operation runs inside
// a transaction, and the `runInTx` / `runInOrgTx` decorators in `tx.ts` close
// over it. Mutations and views take a `Tx` as their first argument.
export type Db = PrismaClient;
export type Tx = Prisma.TransactionClient;

// JSON column value shape. Consumers (queue payloads, sync specs, adapter
// normalizers) import these rather than reaching into the Prisma namespace,
// so the query-layer swap stays contained to this package.
export type JsonPrimitive = boolean | number | string | null;
export type JsonValue = JsonArray | JsonObject | JsonPrimitive;
export type JsonArray = JsonValue[];
export type JsonObject = { [x: string]: JsonValue | undefined };
export type Json = JsonValue;
