
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Org: 'Org',
  User: 'User',
  ProviderAccount: 'ProviderAccount',
  Contact: 'Contact',
  ContactHandle: 'ContactHandle',
  Thread: 'Thread',
  Message: 'Message',
  MessageRaw: 'MessageRaw',
  MessageParticipant: 'MessageParticipant',
  Attachment: 'Attachment',
  SyncJob: 'SyncJob',
  SyncTask: 'SyncTask',
  SyncTaskEvent: 'SyncTaskEvent',
  JobQueue: 'JobQueue'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const OrgScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrgScalarFieldEnum = (typeof OrgScalarFieldEnum)[keyof typeof OrgScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  email: 'email',
  name: 'name',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ProviderAccountScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  userId: 'userId',
  provider: 'provider',
  channel: 'channel',
  authMethod: 'authMethod',
  externalAccountId: 'externalAccountId',
  alias: 'alias',
  credentialsEncrypted: 'credentialsEncrypted',
  lastSyncedAt: 'lastSyncedAt',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProviderAccountScalarFieldEnum = (typeof ProviderAccountScalarFieldEnum)[keyof typeof ProviderAccountScalarFieldEnum]


export const ContactScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  name: 'name',
  isBlocked: 'isBlocked',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
} as const

export type ContactScalarFieldEnum = (typeof ContactScalarFieldEnum)[keyof typeof ContactScalarFieldEnum]


export const ContactHandleScalarFieldEnum = {
  id: 'id',
  contactId: 'contactId',
  channel: 'channel',
  handle: 'handle',
  isPrimary: 'isPrimary',
  createdAt: 'createdAt',
  orgId: 'orgId',
  userId: 'userId'
} as const

export type ContactHandleScalarFieldEnum = (typeof ContactHandleScalarFieldEnum)[keyof typeof ContactHandleScalarFieldEnum]


export const ThreadScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  channel: 'channel',
  externalThreadId: 'externalThreadId',
  subject: 'subject',
  lastMessageAt: 'lastMessageAt',
  messageCount: 'messageCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  providerAccountId: 'providerAccountId'
} as const

export type ThreadScalarFieldEnum = (typeof ThreadScalarFieldEnum)[keyof typeof ThreadScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  threadId: 'threadId',
  providerAccountId: 'providerAccountId',
  channel: 'channel',
  externalMessageId: 'externalMessageId',
  subject: 'subject',
  bodyText: 'bodyText',
  bodyHtml: 'bodyHtml',
  direction: 'direction',
  sentAt: 'sentAt',
  receivedAt: 'receivedAt',
  isRead: 'isRead',
  isStarred: 'isStarred',
  isArchived: 'isArchived',
  isDeleted: 'isDeleted',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  rawMessageId: 'rawMessageId',
  inReplyTo: 'inReplyTo',
  references: 'references',
  messageIdHeader: 'messageIdHeader',
  snippet: 'snippet'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const MessageRawScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  userId: 'userId',
  providerAccountId: 'providerAccountId',
  syncTaskId: 'syncTaskId',
  channel: 'channel',
  externalMessageId: 'externalMessageId',
  payloadSchema: 'payloadSchema',
  payload: 'payload',
  createdAt: 'createdAt'
} as const

export type MessageRawScalarFieldEnum = (typeof MessageRawScalarFieldEnum)[keyof typeof MessageRawScalarFieldEnum]


export const MessageParticipantScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  userId: 'userId',
  messageId: 'messageId',
  contactId: 'contactId',
  handle: 'handle',
  displayName: 'displayName',
  role: 'role',
  createdAt: 'createdAt'
} as const

export type MessageParticipantScalarFieldEnum = (typeof MessageParticipantScalarFieldEnum)[keyof typeof MessageParticipantScalarFieldEnum]


export const AttachmentScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  messageId: 'messageId',
  filename: 'filename',
  contentType: 'contentType',
  sizeBytes: 'sizeBytes',
  createdAt: 'createdAt',
  userId: 'userId',
  externalAttachmentId: 'externalAttachmentId',
  contentId: 'contentId',
  disposition: 'disposition',
  bytes: 'bytes'
} as const

export type AttachmentScalarFieldEnum = (typeof AttachmentScalarFieldEnum)[keyof typeof AttachmentScalarFieldEnum]


export const SyncJobScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SyncJobScalarFieldEnum = (typeof SyncJobScalarFieldEnum)[keyof typeof SyncJobScalarFieldEnum]


export const SyncTaskScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  userId: 'userId',
  jobId: 'jobId',
  providerAccountId: 'providerAccountId',
  spec: 'spec',
  createdAt: 'createdAt'
} as const

export type SyncTaskScalarFieldEnum = (typeof SyncTaskScalarFieldEnum)[keyof typeof SyncTaskScalarFieldEnum]


export const SyncTaskEventScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  userId: 'userId',
  taskId: 'taskId',
  type: 'type',
  payload: 'payload',
  rawMessageId: 'rawMessageId',
  createdAt: 'createdAt'
} as const

export type SyncTaskEventScalarFieldEnum = (typeof SyncTaskEventScalarFieldEnum)[keyof typeof SyncTaskEventScalarFieldEnum]


export const JobQueueScalarFieldEnum = {
  id: 'id',
  topic: 'topic',
  payload: 'payload',
  dedupKey: 'dedupKey',
  status: 'status',
  attempts: 'attempts',
  maxAttempts: 'maxAttempts',
  lastError: 'lastError',
  lockedAt: 'lockedAt',
  lockedBy: 'lockedBy',
  scheduledFor: 'scheduledFor',
  completedAt: 'completedAt',
  createdAt: 'createdAt'
} as const

export type JobQueueScalarFieldEnum = (typeof JobQueueScalarFieldEnum)[keyof typeof JobQueueScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

