
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ContactHandle` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ContactHandle
 * 
 */
export type ContactHandleModel = runtime.Types.Result.DefaultSelection<Prisma.$ContactHandlePayload>

export type AggregateContactHandle = {
  _count: ContactHandleCountAggregateOutputType | null
  _min: ContactHandleMinAggregateOutputType | null
  _max: ContactHandleMaxAggregateOutputType | null
}

export type ContactHandleMinAggregateOutputType = {
  id: string | null
  contactId: string | null
  channel: $Enums.Channel | null
  handle: string | null
  isPrimary: boolean | null
  createdAt: Date | null
  orgId: string | null
  userId: string | null
}

export type ContactHandleMaxAggregateOutputType = {
  id: string | null
  contactId: string | null
  channel: $Enums.Channel | null
  handle: string | null
  isPrimary: boolean | null
  createdAt: Date | null
  orgId: string | null
  userId: string | null
}

export type ContactHandleCountAggregateOutputType = {
  id: number
  contactId: number
  channel: number
  handle: number
  isPrimary: number
  createdAt: number
  orgId: number
  userId: number
  _all: number
}


export type ContactHandleMinAggregateInputType = {
  id?: true
  contactId?: true
  channel?: true
  handle?: true
  isPrimary?: true
  createdAt?: true
  orgId?: true
  userId?: true
}

export type ContactHandleMaxAggregateInputType = {
  id?: true
  contactId?: true
  channel?: true
  handle?: true
  isPrimary?: true
  createdAt?: true
  orgId?: true
  userId?: true
}

export type ContactHandleCountAggregateInputType = {
  id?: true
  contactId?: true
  channel?: true
  handle?: true
  isPrimary?: true
  createdAt?: true
  orgId?: true
  userId?: true
  _all?: true
}

export type ContactHandleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContactHandle to aggregate.
   */
  where?: Prisma.ContactHandleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContactHandles to fetch.
   */
  orderBy?: Prisma.ContactHandleOrderByWithRelationInput | Prisma.ContactHandleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ContactHandleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContactHandles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContactHandles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ContactHandles
  **/
  _count?: true | ContactHandleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ContactHandleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ContactHandleMaxAggregateInputType
}

export type GetContactHandleAggregateType<T extends ContactHandleAggregateArgs> = {
      [P in keyof T & keyof AggregateContactHandle]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContactHandle[P]>
    : Prisma.GetScalarType<T[P], AggregateContactHandle[P]>
}




export type ContactHandleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContactHandleWhereInput
  orderBy?: Prisma.ContactHandleOrderByWithAggregationInput | Prisma.ContactHandleOrderByWithAggregationInput[]
  by: Prisma.ContactHandleScalarFieldEnum[] | Prisma.ContactHandleScalarFieldEnum
  having?: Prisma.ContactHandleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ContactHandleCountAggregateInputType | true
  _min?: ContactHandleMinAggregateInputType
  _max?: ContactHandleMaxAggregateInputType
}

export type ContactHandleGroupByOutputType = {
  id: string
  contactId: string
  channel: $Enums.Channel
  handle: string
  isPrimary: boolean
  createdAt: Date
  orgId: string
  userId: string
  _count: ContactHandleCountAggregateOutputType | null
  _min: ContactHandleMinAggregateOutputType | null
  _max: ContactHandleMaxAggregateOutputType | null
}

export type GetContactHandleGroupByPayload<T extends ContactHandleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContactHandleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ContactHandleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ContactHandleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ContactHandleGroupByOutputType[P]>
      }
    >
  >



export type ContactHandleWhereInput = {
  AND?: Prisma.ContactHandleWhereInput | Prisma.ContactHandleWhereInput[]
  OR?: Prisma.ContactHandleWhereInput[]
  NOT?: Prisma.ContactHandleWhereInput | Prisma.ContactHandleWhereInput[]
  id?: Prisma.UuidFilter<"ContactHandle"> | string
  contactId?: Prisma.UuidFilter<"ContactHandle"> | string
  channel?: Prisma.EnumChannelFilter<"ContactHandle"> | $Enums.Channel
  handle?: Prisma.StringFilter<"ContactHandle"> | string
  isPrimary?: Prisma.BoolFilter<"ContactHandle"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ContactHandle"> | Date | string
  orgId?: Prisma.UuidFilter<"ContactHandle"> | string
  userId?: Prisma.UuidFilter<"ContactHandle"> | string
  contact?: Prisma.XOR<Prisma.ContactScalarRelationFilter, Prisma.ContactWhereInput>
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ContactHandleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  handle?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contact?: Prisma.ContactOrderByWithRelationInput
  org?: Prisma.OrgOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type ContactHandleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_channel_handle?: Prisma.ContactHandleUserIdChannelHandleCompoundUniqueInput
  AND?: Prisma.ContactHandleWhereInput | Prisma.ContactHandleWhereInput[]
  OR?: Prisma.ContactHandleWhereInput[]
  NOT?: Prisma.ContactHandleWhereInput | Prisma.ContactHandleWhereInput[]
  contactId?: Prisma.UuidFilter<"ContactHandle"> | string
  channel?: Prisma.EnumChannelFilter<"ContactHandle"> | $Enums.Channel
  handle?: Prisma.StringFilter<"ContactHandle"> | string
  isPrimary?: Prisma.BoolFilter<"ContactHandle"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ContactHandle"> | Date | string
  orgId?: Prisma.UuidFilter<"ContactHandle"> | string
  userId?: Prisma.UuidFilter<"ContactHandle"> | string
  contact?: Prisma.XOR<Prisma.ContactScalarRelationFilter, Prisma.ContactWhereInput>
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId_channel_handle">

export type ContactHandleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  handle?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.ContactHandleCountOrderByAggregateInput
  _max?: Prisma.ContactHandleMaxOrderByAggregateInput
  _min?: Prisma.ContactHandleMinOrderByAggregateInput
}

export type ContactHandleScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContactHandleScalarWhereWithAggregatesInput | Prisma.ContactHandleScalarWhereWithAggregatesInput[]
  OR?: Prisma.ContactHandleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ContactHandleScalarWhereWithAggregatesInput | Prisma.ContactHandleScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"ContactHandle"> | string
  contactId?: Prisma.UuidWithAggregatesFilter<"ContactHandle"> | string
  channel?: Prisma.EnumChannelWithAggregatesFilter<"ContactHandle"> | $Enums.Channel
  handle?: Prisma.StringWithAggregatesFilter<"ContactHandle"> | string
  isPrimary?: Prisma.BoolWithAggregatesFilter<"ContactHandle"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ContactHandle"> | Date | string
  orgId?: Prisma.UuidWithAggregatesFilter<"ContactHandle"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"ContactHandle"> | string
}

export type ContactHandleCreateInput = {
  id?: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  contact: Prisma.ContactCreateNestedOneWithoutHandlesInput
  org: Prisma.OrgCreateNestedOneWithoutContactHandlesInput
  user: Prisma.UserCreateNestedOneWithoutContactHandlesInput
}

export type ContactHandleUncheckedCreateInput = {
  id?: string
  contactId: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  orgId: string
  userId: string
}

export type ContactHandleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contact?: Prisma.ContactUpdateOneRequiredWithoutHandlesNestedInput
  org?: Prisma.OrgUpdateOneRequiredWithoutContactHandlesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutContactHandlesNestedInput
}

export type ContactHandleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ContactHandleCreateManyInput = {
  id?: string
  contactId: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  orgId: string
  userId: string
}

export type ContactHandleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContactHandleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ContactHandleListRelationFilter = {
  every?: Prisma.ContactHandleWhereInput
  some?: Prisma.ContactHandleWhereInput
  none?: Prisma.ContactHandleWhereInput
}

export type ContactHandleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ContactHandleUserIdChannelHandleCompoundUniqueInput = {
  userId: string
  channel: $Enums.Channel
  handle: string
}

export type ContactHandleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  handle?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ContactHandleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  handle?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ContactHandleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  handle?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ContactHandleCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutOrgInput, Prisma.ContactHandleUncheckedCreateWithoutOrgInput> | Prisma.ContactHandleCreateWithoutOrgInput[] | Prisma.ContactHandleUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutOrgInput | Prisma.ContactHandleCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.ContactHandleCreateManyOrgInputEnvelope
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
}

export type ContactHandleUncheckedCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutOrgInput, Prisma.ContactHandleUncheckedCreateWithoutOrgInput> | Prisma.ContactHandleCreateWithoutOrgInput[] | Prisma.ContactHandleUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutOrgInput | Prisma.ContactHandleCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.ContactHandleCreateManyOrgInputEnvelope
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
}

export type ContactHandleUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutOrgInput, Prisma.ContactHandleUncheckedCreateWithoutOrgInput> | Prisma.ContactHandleCreateWithoutOrgInput[] | Prisma.ContactHandleUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutOrgInput | Prisma.ContactHandleCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.ContactHandleUpsertWithWhereUniqueWithoutOrgInput | Prisma.ContactHandleUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.ContactHandleCreateManyOrgInputEnvelope
  set?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  disconnect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  delete?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  update?: Prisma.ContactHandleUpdateWithWhereUniqueWithoutOrgInput | Prisma.ContactHandleUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.ContactHandleUpdateManyWithWhereWithoutOrgInput | Prisma.ContactHandleUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.ContactHandleScalarWhereInput | Prisma.ContactHandleScalarWhereInput[]
}

export type ContactHandleUncheckedUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutOrgInput, Prisma.ContactHandleUncheckedCreateWithoutOrgInput> | Prisma.ContactHandleCreateWithoutOrgInput[] | Prisma.ContactHandleUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutOrgInput | Prisma.ContactHandleCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.ContactHandleUpsertWithWhereUniqueWithoutOrgInput | Prisma.ContactHandleUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.ContactHandleCreateManyOrgInputEnvelope
  set?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  disconnect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  delete?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  update?: Prisma.ContactHandleUpdateWithWhereUniqueWithoutOrgInput | Prisma.ContactHandleUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.ContactHandleUpdateManyWithWhereWithoutOrgInput | Prisma.ContactHandleUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.ContactHandleScalarWhereInput | Prisma.ContactHandleScalarWhereInput[]
}

export type ContactHandleCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutUserInput, Prisma.ContactHandleUncheckedCreateWithoutUserInput> | Prisma.ContactHandleCreateWithoutUserInput[] | Prisma.ContactHandleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutUserInput | Prisma.ContactHandleCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ContactHandleCreateManyUserInputEnvelope
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
}

export type ContactHandleUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutUserInput, Prisma.ContactHandleUncheckedCreateWithoutUserInput> | Prisma.ContactHandleCreateWithoutUserInput[] | Prisma.ContactHandleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutUserInput | Prisma.ContactHandleCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ContactHandleCreateManyUserInputEnvelope
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
}

export type ContactHandleUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutUserInput, Prisma.ContactHandleUncheckedCreateWithoutUserInput> | Prisma.ContactHandleCreateWithoutUserInput[] | Prisma.ContactHandleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutUserInput | Prisma.ContactHandleCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ContactHandleUpsertWithWhereUniqueWithoutUserInput | Prisma.ContactHandleUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ContactHandleCreateManyUserInputEnvelope
  set?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  disconnect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  delete?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  update?: Prisma.ContactHandleUpdateWithWhereUniqueWithoutUserInput | Prisma.ContactHandleUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ContactHandleUpdateManyWithWhereWithoutUserInput | Prisma.ContactHandleUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ContactHandleScalarWhereInput | Prisma.ContactHandleScalarWhereInput[]
}

export type ContactHandleUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutUserInput, Prisma.ContactHandleUncheckedCreateWithoutUserInput> | Prisma.ContactHandleCreateWithoutUserInput[] | Prisma.ContactHandleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutUserInput | Prisma.ContactHandleCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ContactHandleUpsertWithWhereUniqueWithoutUserInput | Prisma.ContactHandleUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ContactHandleCreateManyUserInputEnvelope
  set?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  disconnect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  delete?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  update?: Prisma.ContactHandleUpdateWithWhereUniqueWithoutUserInput | Prisma.ContactHandleUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ContactHandleUpdateManyWithWhereWithoutUserInput | Prisma.ContactHandleUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ContactHandleScalarWhereInput | Prisma.ContactHandleScalarWhereInput[]
}

export type ContactHandleCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutContactInput, Prisma.ContactHandleUncheckedCreateWithoutContactInput> | Prisma.ContactHandleCreateWithoutContactInput[] | Prisma.ContactHandleUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutContactInput | Prisma.ContactHandleCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.ContactHandleCreateManyContactInputEnvelope
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
}

export type ContactHandleUncheckedCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutContactInput, Prisma.ContactHandleUncheckedCreateWithoutContactInput> | Prisma.ContactHandleCreateWithoutContactInput[] | Prisma.ContactHandleUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutContactInput | Prisma.ContactHandleCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.ContactHandleCreateManyContactInputEnvelope
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
}

export type ContactHandleUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutContactInput, Prisma.ContactHandleUncheckedCreateWithoutContactInput> | Prisma.ContactHandleCreateWithoutContactInput[] | Prisma.ContactHandleUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutContactInput | Prisma.ContactHandleCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.ContactHandleUpsertWithWhereUniqueWithoutContactInput | Prisma.ContactHandleUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.ContactHandleCreateManyContactInputEnvelope
  set?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  disconnect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  delete?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  update?: Prisma.ContactHandleUpdateWithWhereUniqueWithoutContactInput | Prisma.ContactHandleUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.ContactHandleUpdateManyWithWhereWithoutContactInput | Prisma.ContactHandleUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.ContactHandleScalarWhereInput | Prisma.ContactHandleScalarWhereInput[]
}

export type ContactHandleUncheckedUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.ContactHandleCreateWithoutContactInput, Prisma.ContactHandleUncheckedCreateWithoutContactInput> | Prisma.ContactHandleCreateWithoutContactInput[] | Prisma.ContactHandleUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ContactHandleCreateOrConnectWithoutContactInput | Prisma.ContactHandleCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.ContactHandleUpsertWithWhereUniqueWithoutContactInput | Prisma.ContactHandleUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.ContactHandleCreateManyContactInputEnvelope
  set?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  disconnect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  delete?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  connect?: Prisma.ContactHandleWhereUniqueInput | Prisma.ContactHandleWhereUniqueInput[]
  update?: Prisma.ContactHandleUpdateWithWhereUniqueWithoutContactInput | Prisma.ContactHandleUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.ContactHandleUpdateManyWithWhereWithoutContactInput | Prisma.ContactHandleUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.ContactHandleScalarWhereInput | Prisma.ContactHandleScalarWhereInput[]
}

export type ContactHandleCreateWithoutOrgInput = {
  id?: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  contact: Prisma.ContactCreateNestedOneWithoutHandlesInput
  user: Prisma.UserCreateNestedOneWithoutContactHandlesInput
}

export type ContactHandleUncheckedCreateWithoutOrgInput = {
  id?: string
  contactId: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  userId: string
}

export type ContactHandleCreateOrConnectWithoutOrgInput = {
  where: Prisma.ContactHandleWhereUniqueInput
  create: Prisma.XOR<Prisma.ContactHandleCreateWithoutOrgInput, Prisma.ContactHandleUncheckedCreateWithoutOrgInput>
}

export type ContactHandleCreateManyOrgInputEnvelope = {
  data: Prisma.ContactHandleCreateManyOrgInput | Prisma.ContactHandleCreateManyOrgInput[]
  skipDuplicates?: boolean
}

export type ContactHandleUpsertWithWhereUniqueWithoutOrgInput = {
  where: Prisma.ContactHandleWhereUniqueInput
  update: Prisma.XOR<Prisma.ContactHandleUpdateWithoutOrgInput, Prisma.ContactHandleUncheckedUpdateWithoutOrgInput>
  create: Prisma.XOR<Prisma.ContactHandleCreateWithoutOrgInput, Prisma.ContactHandleUncheckedCreateWithoutOrgInput>
}

export type ContactHandleUpdateWithWhereUniqueWithoutOrgInput = {
  where: Prisma.ContactHandleWhereUniqueInput
  data: Prisma.XOR<Prisma.ContactHandleUpdateWithoutOrgInput, Prisma.ContactHandleUncheckedUpdateWithoutOrgInput>
}

export type ContactHandleUpdateManyWithWhereWithoutOrgInput = {
  where: Prisma.ContactHandleScalarWhereInput
  data: Prisma.XOR<Prisma.ContactHandleUpdateManyMutationInput, Prisma.ContactHandleUncheckedUpdateManyWithoutOrgInput>
}

export type ContactHandleScalarWhereInput = {
  AND?: Prisma.ContactHandleScalarWhereInput | Prisma.ContactHandleScalarWhereInput[]
  OR?: Prisma.ContactHandleScalarWhereInput[]
  NOT?: Prisma.ContactHandleScalarWhereInput | Prisma.ContactHandleScalarWhereInput[]
  id?: Prisma.UuidFilter<"ContactHandle"> | string
  contactId?: Prisma.UuidFilter<"ContactHandle"> | string
  channel?: Prisma.EnumChannelFilter<"ContactHandle"> | $Enums.Channel
  handle?: Prisma.StringFilter<"ContactHandle"> | string
  isPrimary?: Prisma.BoolFilter<"ContactHandle"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ContactHandle"> | Date | string
  orgId?: Prisma.UuidFilter<"ContactHandle"> | string
  userId?: Prisma.UuidFilter<"ContactHandle"> | string
}

export type ContactHandleCreateWithoutUserInput = {
  id?: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  contact: Prisma.ContactCreateNestedOneWithoutHandlesInput
  org: Prisma.OrgCreateNestedOneWithoutContactHandlesInput
}

export type ContactHandleUncheckedCreateWithoutUserInput = {
  id?: string
  contactId: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  orgId: string
}

export type ContactHandleCreateOrConnectWithoutUserInput = {
  where: Prisma.ContactHandleWhereUniqueInput
  create: Prisma.XOR<Prisma.ContactHandleCreateWithoutUserInput, Prisma.ContactHandleUncheckedCreateWithoutUserInput>
}

export type ContactHandleCreateManyUserInputEnvelope = {
  data: Prisma.ContactHandleCreateManyUserInput | Prisma.ContactHandleCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ContactHandleUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ContactHandleWhereUniqueInput
  update: Prisma.XOR<Prisma.ContactHandleUpdateWithoutUserInput, Prisma.ContactHandleUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ContactHandleCreateWithoutUserInput, Prisma.ContactHandleUncheckedCreateWithoutUserInput>
}

export type ContactHandleUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ContactHandleWhereUniqueInput
  data: Prisma.XOR<Prisma.ContactHandleUpdateWithoutUserInput, Prisma.ContactHandleUncheckedUpdateWithoutUserInput>
}

export type ContactHandleUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ContactHandleScalarWhereInput
  data: Prisma.XOR<Prisma.ContactHandleUpdateManyMutationInput, Prisma.ContactHandleUncheckedUpdateManyWithoutUserInput>
}

export type ContactHandleCreateWithoutContactInput = {
  id?: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutContactHandlesInput
  user: Prisma.UserCreateNestedOneWithoutContactHandlesInput
}

export type ContactHandleUncheckedCreateWithoutContactInput = {
  id?: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  orgId: string
  userId: string
}

export type ContactHandleCreateOrConnectWithoutContactInput = {
  where: Prisma.ContactHandleWhereUniqueInput
  create: Prisma.XOR<Prisma.ContactHandleCreateWithoutContactInput, Prisma.ContactHandleUncheckedCreateWithoutContactInput>
}

export type ContactHandleCreateManyContactInputEnvelope = {
  data: Prisma.ContactHandleCreateManyContactInput | Prisma.ContactHandleCreateManyContactInput[]
  skipDuplicates?: boolean
}

export type ContactHandleUpsertWithWhereUniqueWithoutContactInput = {
  where: Prisma.ContactHandleWhereUniqueInput
  update: Prisma.XOR<Prisma.ContactHandleUpdateWithoutContactInput, Prisma.ContactHandleUncheckedUpdateWithoutContactInput>
  create: Prisma.XOR<Prisma.ContactHandleCreateWithoutContactInput, Prisma.ContactHandleUncheckedCreateWithoutContactInput>
}

export type ContactHandleUpdateWithWhereUniqueWithoutContactInput = {
  where: Prisma.ContactHandleWhereUniqueInput
  data: Prisma.XOR<Prisma.ContactHandleUpdateWithoutContactInput, Prisma.ContactHandleUncheckedUpdateWithoutContactInput>
}

export type ContactHandleUpdateManyWithWhereWithoutContactInput = {
  where: Prisma.ContactHandleScalarWhereInput
  data: Prisma.XOR<Prisma.ContactHandleUpdateManyMutationInput, Prisma.ContactHandleUncheckedUpdateManyWithoutContactInput>
}

export type ContactHandleCreateManyOrgInput = {
  id?: string
  contactId: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  userId: string
}

export type ContactHandleUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contact?: Prisma.ContactUpdateOneRequiredWithoutHandlesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutContactHandlesNestedInput
}

export type ContactHandleUncheckedUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ContactHandleUncheckedUpdateManyWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ContactHandleCreateManyUserInput = {
  id?: string
  contactId: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  orgId: string
}

export type ContactHandleUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contact?: Prisma.ContactUpdateOneRequiredWithoutHandlesNestedInput
  org?: Prisma.OrgUpdateOneRequiredWithoutContactHandlesNestedInput
}

export type ContactHandleUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ContactHandleUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ContactHandleCreateManyContactInput = {
  id?: string
  channel: $Enums.Channel
  handle: string
  isPrimary?: boolean
  createdAt?: Date | string
  orgId: string
  userId: string
}

export type ContactHandleUpdateWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutContactHandlesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutContactHandlesNestedInput
}

export type ContactHandleUncheckedUpdateWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ContactHandleUncheckedUpdateManyWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ContactHandleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  contactId?: boolean
  channel?: boolean
  handle?: boolean
  isPrimary?: boolean
  createdAt?: boolean
  orgId?: boolean
  userId?: boolean
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contactHandle"]>

export type ContactHandleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  contactId?: boolean
  channel?: boolean
  handle?: boolean
  isPrimary?: boolean
  createdAt?: boolean
  orgId?: boolean
  userId?: boolean
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contactHandle"]>

export type ContactHandleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  contactId?: boolean
  channel?: boolean
  handle?: boolean
  isPrimary?: boolean
  createdAt?: boolean
  orgId?: boolean
  userId?: boolean
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contactHandle"]>

export type ContactHandleSelectScalar = {
  id?: boolean
  contactId?: boolean
  channel?: boolean
  handle?: boolean
  isPrimary?: boolean
  createdAt?: boolean
  orgId?: boolean
  userId?: boolean
}

export type ContactHandleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "contactId" | "channel" | "handle" | "isPrimary" | "createdAt" | "orgId" | "userId", ExtArgs["result"]["contactHandle"]>
export type ContactHandleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ContactHandleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ContactHandleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ContactHandlePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ContactHandle"
  objects: {
    contact: Prisma.$ContactPayload<ExtArgs>
    org: Prisma.$OrgPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    contactId: string
    channel: $Enums.Channel
    handle: string
    isPrimary: boolean
    createdAt: Date
    orgId: string
    userId: string
  }, ExtArgs["result"]["contactHandle"]>
  composites: {}
}

export type ContactHandleGetPayload<S extends boolean | null | undefined | ContactHandleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload, S>

export type ContactHandleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ContactHandleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ContactHandleCountAggregateInputType | true
  }

export interface ContactHandleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ContactHandle'], meta: { name: 'ContactHandle' } }
  /**
   * Find zero or one ContactHandle that matches the filter.
   * @param {ContactHandleFindUniqueArgs} args - Arguments to find a ContactHandle
   * @example
   * // Get one ContactHandle
   * const contactHandle = await prisma.contactHandle.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContactHandleFindUniqueArgs>(args: Prisma.SelectSubset<T, ContactHandleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ContactHandleClient<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ContactHandle that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContactHandleFindUniqueOrThrowArgs} args - Arguments to find a ContactHandle
   * @example
   * // Get one ContactHandle
   * const contactHandle = await prisma.contactHandle.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContactHandleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ContactHandleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContactHandleClient<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContactHandle that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactHandleFindFirstArgs} args - Arguments to find a ContactHandle
   * @example
   * // Get one ContactHandle
   * const contactHandle = await prisma.contactHandle.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContactHandleFindFirstArgs>(args?: Prisma.SelectSubset<T, ContactHandleFindFirstArgs<ExtArgs>>): Prisma.Prisma__ContactHandleClient<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContactHandle that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactHandleFindFirstOrThrowArgs} args - Arguments to find a ContactHandle
   * @example
   * // Get one ContactHandle
   * const contactHandle = await prisma.contactHandle.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContactHandleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ContactHandleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContactHandleClient<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ContactHandles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactHandleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ContactHandles
   * const contactHandles = await prisma.contactHandle.findMany()
   * 
   * // Get first 10 ContactHandles
   * const contactHandles = await prisma.contactHandle.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const contactHandleWithIdOnly = await prisma.contactHandle.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ContactHandleFindManyArgs>(args?: Prisma.SelectSubset<T, ContactHandleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ContactHandle.
   * @param {ContactHandleCreateArgs} args - Arguments to create a ContactHandle.
   * @example
   * // Create one ContactHandle
   * const ContactHandle = await prisma.contactHandle.create({
   *   data: {
   *     // ... data to create a ContactHandle
   *   }
   * })
   * 
   */
  create<T extends ContactHandleCreateArgs>(args: Prisma.SelectSubset<T, ContactHandleCreateArgs<ExtArgs>>): Prisma.Prisma__ContactHandleClient<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ContactHandles.
   * @param {ContactHandleCreateManyArgs} args - Arguments to create many ContactHandles.
   * @example
   * // Create many ContactHandles
   * const contactHandle = await prisma.contactHandle.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ContactHandleCreateManyArgs>(args?: Prisma.SelectSubset<T, ContactHandleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ContactHandles and returns the data saved in the database.
   * @param {ContactHandleCreateManyAndReturnArgs} args - Arguments to create many ContactHandles.
   * @example
   * // Create many ContactHandles
   * const contactHandle = await prisma.contactHandle.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ContactHandles and only return the `id`
   * const contactHandleWithIdOnly = await prisma.contactHandle.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ContactHandleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ContactHandleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ContactHandle.
   * @param {ContactHandleDeleteArgs} args - Arguments to delete one ContactHandle.
   * @example
   * // Delete one ContactHandle
   * const ContactHandle = await prisma.contactHandle.delete({
   *   where: {
   *     // ... filter to delete one ContactHandle
   *   }
   * })
   * 
   */
  delete<T extends ContactHandleDeleteArgs>(args: Prisma.SelectSubset<T, ContactHandleDeleteArgs<ExtArgs>>): Prisma.Prisma__ContactHandleClient<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ContactHandle.
   * @param {ContactHandleUpdateArgs} args - Arguments to update one ContactHandle.
   * @example
   * // Update one ContactHandle
   * const contactHandle = await prisma.contactHandle.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ContactHandleUpdateArgs>(args: Prisma.SelectSubset<T, ContactHandleUpdateArgs<ExtArgs>>): Prisma.Prisma__ContactHandleClient<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ContactHandles.
   * @param {ContactHandleDeleteManyArgs} args - Arguments to filter ContactHandles to delete.
   * @example
   * // Delete a few ContactHandles
   * const { count } = await prisma.contactHandle.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ContactHandleDeleteManyArgs>(args?: Prisma.SelectSubset<T, ContactHandleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContactHandles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactHandleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ContactHandles
   * const contactHandle = await prisma.contactHandle.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ContactHandleUpdateManyArgs>(args: Prisma.SelectSubset<T, ContactHandleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContactHandles and returns the data updated in the database.
   * @param {ContactHandleUpdateManyAndReturnArgs} args - Arguments to update many ContactHandles.
   * @example
   * // Update many ContactHandles
   * const contactHandle = await prisma.contactHandle.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ContactHandles and only return the `id`
   * const contactHandleWithIdOnly = await prisma.contactHandle.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ContactHandleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ContactHandleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ContactHandle.
   * @param {ContactHandleUpsertArgs} args - Arguments to update or create a ContactHandle.
   * @example
   * // Update or create a ContactHandle
   * const contactHandle = await prisma.contactHandle.upsert({
   *   create: {
   *     // ... data to create a ContactHandle
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ContactHandle we want to update
   *   }
   * })
   */
  upsert<T extends ContactHandleUpsertArgs>(args: Prisma.SelectSubset<T, ContactHandleUpsertArgs<ExtArgs>>): Prisma.Prisma__ContactHandleClient<runtime.Types.Result.GetResult<Prisma.$ContactHandlePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ContactHandles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactHandleCountArgs} args - Arguments to filter ContactHandles to count.
   * @example
   * // Count the number of ContactHandles
   * const count = await prisma.contactHandle.count({
   *   where: {
   *     // ... the filter for the ContactHandles we want to count
   *   }
   * })
  **/
  count<T extends ContactHandleCountArgs>(
    args?: Prisma.Subset<T, ContactHandleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContactHandleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ContactHandle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactHandleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ContactHandleAggregateArgs>(args: Prisma.Subset<T, ContactHandleAggregateArgs>): Prisma.PrismaPromise<GetContactHandleAggregateType<T>>

  /**
   * Group by ContactHandle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactHandleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ContactHandleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContactHandleGroupByArgs['orderBy'] }
      : { orderBy?: ContactHandleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ContactHandleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetContactHandleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ContactHandle model
 */
readonly fields: ContactHandleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ContactHandle.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContactHandleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  contact<T extends Prisma.ContactDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ContactDefaultArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  org<T extends Prisma.OrgDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrgDefaultArgs<ExtArgs>>): Prisma.Prisma__OrgClient<runtime.Types.Result.GetResult<Prisma.$OrgPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ContactHandle model
 */
export interface ContactHandleFieldRefs {
  readonly id: Prisma.FieldRef<"ContactHandle", 'String'>
  readonly contactId: Prisma.FieldRef<"ContactHandle", 'String'>
  readonly channel: Prisma.FieldRef<"ContactHandle", 'Channel'>
  readonly handle: Prisma.FieldRef<"ContactHandle", 'String'>
  readonly isPrimary: Prisma.FieldRef<"ContactHandle", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ContactHandle", 'DateTime'>
  readonly orgId: Prisma.FieldRef<"ContactHandle", 'String'>
  readonly userId: Prisma.FieldRef<"ContactHandle", 'String'>
}
    

// Custom InputTypes
/**
 * ContactHandle findUnique
 */
export type ContactHandleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
  /**
   * Filter, which ContactHandle to fetch.
   */
  where: Prisma.ContactHandleWhereUniqueInput
}

/**
 * ContactHandle findUniqueOrThrow
 */
export type ContactHandleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
  /**
   * Filter, which ContactHandle to fetch.
   */
  where: Prisma.ContactHandleWhereUniqueInput
}

/**
 * ContactHandle findFirst
 */
export type ContactHandleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
  /**
   * Filter, which ContactHandle to fetch.
   */
  where?: Prisma.ContactHandleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContactHandles to fetch.
   */
  orderBy?: Prisma.ContactHandleOrderByWithRelationInput | Prisma.ContactHandleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContactHandles.
   */
  cursor?: Prisma.ContactHandleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContactHandles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContactHandles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContactHandles.
   */
  distinct?: Prisma.ContactHandleScalarFieldEnum | Prisma.ContactHandleScalarFieldEnum[]
}

/**
 * ContactHandle findFirstOrThrow
 */
export type ContactHandleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
  /**
   * Filter, which ContactHandle to fetch.
   */
  where?: Prisma.ContactHandleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContactHandles to fetch.
   */
  orderBy?: Prisma.ContactHandleOrderByWithRelationInput | Prisma.ContactHandleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContactHandles.
   */
  cursor?: Prisma.ContactHandleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContactHandles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContactHandles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContactHandles.
   */
  distinct?: Prisma.ContactHandleScalarFieldEnum | Prisma.ContactHandleScalarFieldEnum[]
}

/**
 * ContactHandle findMany
 */
export type ContactHandleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
  /**
   * Filter, which ContactHandles to fetch.
   */
  where?: Prisma.ContactHandleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContactHandles to fetch.
   */
  orderBy?: Prisma.ContactHandleOrderByWithRelationInput | Prisma.ContactHandleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ContactHandles.
   */
  cursor?: Prisma.ContactHandleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContactHandles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContactHandles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContactHandles.
   */
  distinct?: Prisma.ContactHandleScalarFieldEnum | Prisma.ContactHandleScalarFieldEnum[]
}

/**
 * ContactHandle create
 */
export type ContactHandleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
  /**
   * The data needed to create a ContactHandle.
   */
  data: Prisma.XOR<Prisma.ContactHandleCreateInput, Prisma.ContactHandleUncheckedCreateInput>
}

/**
 * ContactHandle createMany
 */
export type ContactHandleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ContactHandles.
   */
  data: Prisma.ContactHandleCreateManyInput | Prisma.ContactHandleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ContactHandle createManyAndReturn
 */
export type ContactHandleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * The data used to create many ContactHandles.
   */
  data: Prisma.ContactHandleCreateManyInput | Prisma.ContactHandleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ContactHandle update
 */
export type ContactHandleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
  /**
   * The data needed to update a ContactHandle.
   */
  data: Prisma.XOR<Prisma.ContactHandleUpdateInput, Prisma.ContactHandleUncheckedUpdateInput>
  /**
   * Choose, which ContactHandle to update.
   */
  where: Prisma.ContactHandleWhereUniqueInput
}

/**
 * ContactHandle updateMany
 */
export type ContactHandleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ContactHandles.
   */
  data: Prisma.XOR<Prisma.ContactHandleUpdateManyMutationInput, Prisma.ContactHandleUncheckedUpdateManyInput>
  /**
   * Filter which ContactHandles to update
   */
  where?: Prisma.ContactHandleWhereInput
  /**
   * Limit how many ContactHandles to update.
   */
  limit?: number
}

/**
 * ContactHandle updateManyAndReturn
 */
export type ContactHandleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * The data used to update ContactHandles.
   */
  data: Prisma.XOR<Prisma.ContactHandleUpdateManyMutationInput, Prisma.ContactHandleUncheckedUpdateManyInput>
  /**
   * Filter which ContactHandles to update
   */
  where?: Prisma.ContactHandleWhereInput
  /**
   * Limit how many ContactHandles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ContactHandle upsert
 */
export type ContactHandleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
  /**
   * The filter to search for the ContactHandle to update in case it exists.
   */
  where: Prisma.ContactHandleWhereUniqueInput
  /**
   * In case the ContactHandle found by the `where` argument doesn't exist, create a new ContactHandle with this data.
   */
  create: Prisma.XOR<Prisma.ContactHandleCreateInput, Prisma.ContactHandleUncheckedCreateInput>
  /**
   * In case the ContactHandle was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContactHandleUpdateInput, Prisma.ContactHandleUncheckedUpdateInput>
}

/**
 * ContactHandle delete
 */
export type ContactHandleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
  /**
   * Filter which ContactHandle to delete.
   */
  where: Prisma.ContactHandleWhereUniqueInput
}

/**
 * ContactHandle deleteMany
 */
export type ContactHandleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContactHandles to delete
   */
  where?: Prisma.ContactHandleWhereInput
  /**
   * Limit how many ContactHandles to delete.
   */
  limit?: number
}

/**
 * ContactHandle without action
 */
export type ContactHandleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactHandle
   */
  select?: Prisma.ContactHandleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactHandle
   */
  omit?: Prisma.ContactHandleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactHandleInclude<ExtArgs> | null
}
