
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MessageParticipant` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MessageParticipant
 * 
 */
export type MessageParticipantModel = runtime.Types.Result.DefaultSelection<Prisma.$MessageParticipantPayload>

export type AggregateMessageParticipant = {
  _count: MessageParticipantCountAggregateOutputType | null
  _min: MessageParticipantMinAggregateOutputType | null
  _max: MessageParticipantMaxAggregateOutputType | null
}

export type MessageParticipantMinAggregateOutputType = {
  id: string | null
  orgId: string | null
  userId: string | null
  messageId: string | null
  contactId: string | null
  handle: string | null
  displayName: string | null
  role: string | null
  createdAt: Date | null
}

export type MessageParticipantMaxAggregateOutputType = {
  id: string | null
  orgId: string | null
  userId: string | null
  messageId: string | null
  contactId: string | null
  handle: string | null
  displayName: string | null
  role: string | null
  createdAt: Date | null
}

export type MessageParticipantCountAggregateOutputType = {
  id: number
  orgId: number
  userId: number
  messageId: number
  contactId: number
  handle: number
  displayName: number
  role: number
  createdAt: number
  _all: number
}


export type MessageParticipantMinAggregateInputType = {
  id?: true
  orgId?: true
  userId?: true
  messageId?: true
  contactId?: true
  handle?: true
  displayName?: true
  role?: true
  createdAt?: true
}

export type MessageParticipantMaxAggregateInputType = {
  id?: true
  orgId?: true
  userId?: true
  messageId?: true
  contactId?: true
  handle?: true
  displayName?: true
  role?: true
  createdAt?: true
}

export type MessageParticipantCountAggregateInputType = {
  id?: true
  orgId?: true
  userId?: true
  messageId?: true
  contactId?: true
  handle?: true
  displayName?: true
  role?: true
  createdAt?: true
  _all?: true
}

export type MessageParticipantAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MessageParticipant to aggregate.
   */
  where?: Prisma.MessageParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageParticipants to fetch.
   */
  orderBy?: Prisma.MessageParticipantOrderByWithRelationInput | Prisma.MessageParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MessageParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageParticipants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageParticipants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MessageParticipants
  **/
  _count?: true | MessageParticipantCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MessageParticipantMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MessageParticipantMaxAggregateInputType
}

export type GetMessageParticipantAggregateType<T extends MessageParticipantAggregateArgs> = {
      [P in keyof T & keyof AggregateMessageParticipant]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMessageParticipant[P]>
    : Prisma.GetScalarType<T[P], AggregateMessageParticipant[P]>
}




export type MessageParticipantGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageParticipantWhereInput
  orderBy?: Prisma.MessageParticipantOrderByWithAggregationInput | Prisma.MessageParticipantOrderByWithAggregationInput[]
  by: Prisma.MessageParticipantScalarFieldEnum[] | Prisma.MessageParticipantScalarFieldEnum
  having?: Prisma.MessageParticipantScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MessageParticipantCountAggregateInputType | true
  _min?: MessageParticipantMinAggregateInputType
  _max?: MessageParticipantMaxAggregateInputType
}

export type MessageParticipantGroupByOutputType = {
  id: string
  orgId: string
  userId: string
  messageId: string
  contactId: string | null
  handle: string
  displayName: string | null
  role: string
  createdAt: Date
  _count: MessageParticipantCountAggregateOutputType | null
  _min: MessageParticipantMinAggregateOutputType | null
  _max: MessageParticipantMaxAggregateOutputType | null
}

export type GetMessageParticipantGroupByPayload<T extends MessageParticipantGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MessageParticipantGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MessageParticipantGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MessageParticipantGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MessageParticipantGroupByOutputType[P]>
      }
    >
  >



export type MessageParticipantWhereInput = {
  AND?: Prisma.MessageParticipantWhereInput | Prisma.MessageParticipantWhereInput[]
  OR?: Prisma.MessageParticipantWhereInput[]
  NOT?: Prisma.MessageParticipantWhereInput | Prisma.MessageParticipantWhereInput[]
  id?: Prisma.UuidFilter<"MessageParticipant"> | string
  orgId?: Prisma.UuidFilter<"MessageParticipant"> | string
  userId?: Prisma.UuidFilter<"MessageParticipant"> | string
  messageId?: Prisma.UuidFilter<"MessageParticipant"> | string
  contactId?: Prisma.UuidNullableFilter<"MessageParticipant"> | string | null
  handle?: Prisma.StringFilter<"MessageParticipant"> | string
  displayName?: Prisma.StringNullableFilter<"MessageParticipant"> | string | null
  role?: Prisma.StringFilter<"MessageParticipant"> | string
  createdAt?: Prisma.DateTimeFilter<"MessageParticipant"> | Date | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  message?: Prisma.XOR<Prisma.MessageScalarRelationFilter, Prisma.MessageWhereInput>
  contact?: Prisma.XOR<Prisma.ContactNullableScalarRelationFilter, Prisma.ContactWhereInput> | null
}

export type MessageParticipantOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  contactId?: Prisma.SortOrderInput | Prisma.SortOrder
  handle?: Prisma.SortOrder
  displayName?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  org?: Prisma.OrgOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  message?: Prisma.MessageOrderByWithRelationInput
  contact?: Prisma.ContactOrderByWithRelationInput
}

export type MessageParticipantWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MessageParticipantWhereInput | Prisma.MessageParticipantWhereInput[]
  OR?: Prisma.MessageParticipantWhereInput[]
  NOT?: Prisma.MessageParticipantWhereInput | Prisma.MessageParticipantWhereInput[]
  orgId?: Prisma.UuidFilter<"MessageParticipant"> | string
  userId?: Prisma.UuidFilter<"MessageParticipant"> | string
  messageId?: Prisma.UuidFilter<"MessageParticipant"> | string
  contactId?: Prisma.UuidNullableFilter<"MessageParticipant"> | string | null
  handle?: Prisma.StringFilter<"MessageParticipant"> | string
  displayName?: Prisma.StringNullableFilter<"MessageParticipant"> | string | null
  role?: Prisma.StringFilter<"MessageParticipant"> | string
  createdAt?: Prisma.DateTimeFilter<"MessageParticipant"> | Date | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  message?: Prisma.XOR<Prisma.MessageScalarRelationFilter, Prisma.MessageWhereInput>
  contact?: Prisma.XOR<Prisma.ContactNullableScalarRelationFilter, Prisma.ContactWhereInput> | null
}, "id">

export type MessageParticipantOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  contactId?: Prisma.SortOrderInput | Prisma.SortOrder
  handle?: Prisma.SortOrder
  displayName?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MessageParticipantCountOrderByAggregateInput
  _max?: Prisma.MessageParticipantMaxOrderByAggregateInput
  _min?: Prisma.MessageParticipantMinOrderByAggregateInput
}

export type MessageParticipantScalarWhereWithAggregatesInput = {
  AND?: Prisma.MessageParticipantScalarWhereWithAggregatesInput | Prisma.MessageParticipantScalarWhereWithAggregatesInput[]
  OR?: Prisma.MessageParticipantScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MessageParticipantScalarWhereWithAggregatesInput | Prisma.MessageParticipantScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"MessageParticipant"> | string
  orgId?: Prisma.UuidWithAggregatesFilter<"MessageParticipant"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"MessageParticipant"> | string
  messageId?: Prisma.UuidWithAggregatesFilter<"MessageParticipant"> | string
  contactId?: Prisma.UuidNullableWithAggregatesFilter<"MessageParticipant"> | string | null
  handle?: Prisma.StringWithAggregatesFilter<"MessageParticipant"> | string
  displayName?: Prisma.StringNullableWithAggregatesFilter<"MessageParticipant"> | string | null
  role?: Prisma.StringWithAggregatesFilter<"MessageParticipant"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MessageParticipant"> | Date | string
}

export type MessageParticipantCreateInput = {
  id?: string
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutMessageParticipantsInput
  user: Prisma.UserCreateNestedOneWithoutMessageParticipantsInput
  message: Prisma.MessageCreateNestedOneWithoutParticipantsInput
  contact?: Prisma.ContactCreateNestedOneWithoutMessageParticipantsInput
}

export type MessageParticipantUncheckedCreateInput = {
  id?: string
  orgId: string
  userId: string
  messageId: string
  contactId?: string | null
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutMessageParticipantsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutMessageParticipantsNestedInput
  message?: Prisma.MessageUpdateOneRequiredWithoutParticipantsNestedInput
  contact?: Prisma.ContactUpdateOneWithoutMessageParticipantsNestedInput
}

export type MessageParticipantUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantCreateManyInput = {
  id?: string
  orgId: string
  userId: string
  messageId: string
  contactId?: string | null
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantListRelationFilter = {
  every?: Prisma.MessageParticipantWhereInput
  some?: Prisma.MessageParticipantWhereInput
  none?: Prisma.MessageParticipantWhereInput
}

export type MessageParticipantOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MessageParticipantCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  handle?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MessageParticipantMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  handle?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MessageParticipantMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  handle?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MessageParticipantCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutOrgInput, Prisma.MessageParticipantUncheckedCreateWithoutOrgInput> | Prisma.MessageParticipantCreateWithoutOrgInput[] | Prisma.MessageParticipantUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutOrgInput | Prisma.MessageParticipantCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.MessageParticipantCreateManyOrgInputEnvelope
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
}

export type MessageParticipantUncheckedCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutOrgInput, Prisma.MessageParticipantUncheckedCreateWithoutOrgInput> | Prisma.MessageParticipantCreateWithoutOrgInput[] | Prisma.MessageParticipantUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutOrgInput | Prisma.MessageParticipantCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.MessageParticipantCreateManyOrgInputEnvelope
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
}

export type MessageParticipantUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutOrgInput, Prisma.MessageParticipantUncheckedCreateWithoutOrgInput> | Prisma.MessageParticipantCreateWithoutOrgInput[] | Prisma.MessageParticipantUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutOrgInput | Prisma.MessageParticipantCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.MessageParticipantUpsertWithWhereUniqueWithoutOrgInput | Prisma.MessageParticipantUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.MessageParticipantCreateManyOrgInputEnvelope
  set?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  disconnect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  delete?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  update?: Prisma.MessageParticipantUpdateWithWhereUniqueWithoutOrgInput | Prisma.MessageParticipantUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.MessageParticipantUpdateManyWithWhereWithoutOrgInput | Prisma.MessageParticipantUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
}

export type MessageParticipantUncheckedUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutOrgInput, Prisma.MessageParticipantUncheckedCreateWithoutOrgInput> | Prisma.MessageParticipantCreateWithoutOrgInput[] | Prisma.MessageParticipantUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutOrgInput | Prisma.MessageParticipantCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.MessageParticipantUpsertWithWhereUniqueWithoutOrgInput | Prisma.MessageParticipantUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.MessageParticipantCreateManyOrgInputEnvelope
  set?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  disconnect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  delete?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  update?: Prisma.MessageParticipantUpdateWithWhereUniqueWithoutOrgInput | Prisma.MessageParticipantUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.MessageParticipantUpdateManyWithWhereWithoutOrgInput | Prisma.MessageParticipantUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
}

export type MessageParticipantCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutUserInput, Prisma.MessageParticipantUncheckedCreateWithoutUserInput> | Prisma.MessageParticipantCreateWithoutUserInput[] | Prisma.MessageParticipantUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutUserInput | Prisma.MessageParticipantCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MessageParticipantCreateManyUserInputEnvelope
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
}

export type MessageParticipantUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutUserInput, Prisma.MessageParticipantUncheckedCreateWithoutUserInput> | Prisma.MessageParticipantCreateWithoutUserInput[] | Prisma.MessageParticipantUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutUserInput | Prisma.MessageParticipantCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MessageParticipantCreateManyUserInputEnvelope
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
}

export type MessageParticipantUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutUserInput, Prisma.MessageParticipantUncheckedCreateWithoutUserInput> | Prisma.MessageParticipantCreateWithoutUserInput[] | Prisma.MessageParticipantUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutUserInput | Prisma.MessageParticipantCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MessageParticipantUpsertWithWhereUniqueWithoutUserInput | Prisma.MessageParticipantUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MessageParticipantCreateManyUserInputEnvelope
  set?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  disconnect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  delete?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  update?: Prisma.MessageParticipantUpdateWithWhereUniqueWithoutUserInput | Prisma.MessageParticipantUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MessageParticipantUpdateManyWithWhereWithoutUserInput | Prisma.MessageParticipantUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
}

export type MessageParticipantUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutUserInput, Prisma.MessageParticipantUncheckedCreateWithoutUserInput> | Prisma.MessageParticipantCreateWithoutUserInput[] | Prisma.MessageParticipantUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutUserInput | Prisma.MessageParticipantCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MessageParticipantUpsertWithWhereUniqueWithoutUserInput | Prisma.MessageParticipantUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MessageParticipantCreateManyUserInputEnvelope
  set?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  disconnect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  delete?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  update?: Prisma.MessageParticipantUpdateWithWhereUniqueWithoutUserInput | Prisma.MessageParticipantUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MessageParticipantUpdateManyWithWhereWithoutUserInput | Prisma.MessageParticipantUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
}

export type MessageParticipantCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutContactInput, Prisma.MessageParticipantUncheckedCreateWithoutContactInput> | Prisma.MessageParticipantCreateWithoutContactInput[] | Prisma.MessageParticipantUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutContactInput | Prisma.MessageParticipantCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.MessageParticipantCreateManyContactInputEnvelope
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
}

export type MessageParticipantUncheckedCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutContactInput, Prisma.MessageParticipantUncheckedCreateWithoutContactInput> | Prisma.MessageParticipantCreateWithoutContactInput[] | Prisma.MessageParticipantUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutContactInput | Prisma.MessageParticipantCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.MessageParticipantCreateManyContactInputEnvelope
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
}

export type MessageParticipantUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutContactInput, Prisma.MessageParticipantUncheckedCreateWithoutContactInput> | Prisma.MessageParticipantCreateWithoutContactInput[] | Prisma.MessageParticipantUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutContactInput | Prisma.MessageParticipantCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.MessageParticipantUpsertWithWhereUniqueWithoutContactInput | Prisma.MessageParticipantUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.MessageParticipantCreateManyContactInputEnvelope
  set?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  disconnect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  delete?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  update?: Prisma.MessageParticipantUpdateWithWhereUniqueWithoutContactInput | Prisma.MessageParticipantUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.MessageParticipantUpdateManyWithWhereWithoutContactInput | Prisma.MessageParticipantUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
}

export type MessageParticipantUncheckedUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutContactInput, Prisma.MessageParticipantUncheckedCreateWithoutContactInput> | Prisma.MessageParticipantCreateWithoutContactInput[] | Prisma.MessageParticipantUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutContactInput | Prisma.MessageParticipantCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.MessageParticipantUpsertWithWhereUniqueWithoutContactInput | Prisma.MessageParticipantUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.MessageParticipantCreateManyContactInputEnvelope
  set?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  disconnect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  delete?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  update?: Prisma.MessageParticipantUpdateWithWhereUniqueWithoutContactInput | Prisma.MessageParticipantUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.MessageParticipantUpdateManyWithWhereWithoutContactInput | Prisma.MessageParticipantUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
}

export type MessageParticipantCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutMessageInput, Prisma.MessageParticipantUncheckedCreateWithoutMessageInput> | Prisma.MessageParticipantCreateWithoutMessageInput[] | Prisma.MessageParticipantUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutMessageInput | Prisma.MessageParticipantCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.MessageParticipantCreateManyMessageInputEnvelope
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
}

export type MessageParticipantUncheckedCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutMessageInput, Prisma.MessageParticipantUncheckedCreateWithoutMessageInput> | Prisma.MessageParticipantCreateWithoutMessageInput[] | Prisma.MessageParticipantUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutMessageInput | Prisma.MessageParticipantCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.MessageParticipantCreateManyMessageInputEnvelope
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
}

export type MessageParticipantUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutMessageInput, Prisma.MessageParticipantUncheckedCreateWithoutMessageInput> | Prisma.MessageParticipantCreateWithoutMessageInput[] | Prisma.MessageParticipantUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutMessageInput | Prisma.MessageParticipantCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.MessageParticipantUpsertWithWhereUniqueWithoutMessageInput | Prisma.MessageParticipantUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.MessageParticipantCreateManyMessageInputEnvelope
  set?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  disconnect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  delete?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  update?: Prisma.MessageParticipantUpdateWithWhereUniqueWithoutMessageInput | Prisma.MessageParticipantUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.MessageParticipantUpdateManyWithWhereWithoutMessageInput | Prisma.MessageParticipantUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
}

export type MessageParticipantUncheckedUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.MessageParticipantCreateWithoutMessageInput, Prisma.MessageParticipantUncheckedCreateWithoutMessageInput> | Prisma.MessageParticipantCreateWithoutMessageInput[] | Prisma.MessageParticipantUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.MessageParticipantCreateOrConnectWithoutMessageInput | Prisma.MessageParticipantCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.MessageParticipantUpsertWithWhereUniqueWithoutMessageInput | Prisma.MessageParticipantUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.MessageParticipantCreateManyMessageInputEnvelope
  set?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  disconnect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  delete?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  connect?: Prisma.MessageParticipantWhereUniqueInput | Prisma.MessageParticipantWhereUniqueInput[]
  update?: Prisma.MessageParticipantUpdateWithWhereUniqueWithoutMessageInput | Prisma.MessageParticipantUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.MessageParticipantUpdateManyWithWhereWithoutMessageInput | Prisma.MessageParticipantUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
}

export type MessageParticipantCreateWithoutOrgInput = {
  id?: string
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutMessageParticipantsInput
  message: Prisma.MessageCreateNestedOneWithoutParticipantsInput
  contact?: Prisma.ContactCreateNestedOneWithoutMessageParticipantsInput
}

export type MessageParticipantUncheckedCreateWithoutOrgInput = {
  id?: string
  userId: string
  messageId: string
  contactId?: string | null
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantCreateOrConnectWithoutOrgInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageParticipantCreateWithoutOrgInput, Prisma.MessageParticipantUncheckedCreateWithoutOrgInput>
}

export type MessageParticipantCreateManyOrgInputEnvelope = {
  data: Prisma.MessageParticipantCreateManyOrgInput | Prisma.MessageParticipantCreateManyOrgInput[]
  skipDuplicates?: boolean
}

export type MessageParticipantUpsertWithWhereUniqueWithoutOrgInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageParticipantUpdateWithoutOrgInput, Prisma.MessageParticipantUncheckedUpdateWithoutOrgInput>
  create: Prisma.XOR<Prisma.MessageParticipantCreateWithoutOrgInput, Prisma.MessageParticipantUncheckedCreateWithoutOrgInput>
}

export type MessageParticipantUpdateWithWhereUniqueWithoutOrgInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageParticipantUpdateWithoutOrgInput, Prisma.MessageParticipantUncheckedUpdateWithoutOrgInput>
}

export type MessageParticipantUpdateManyWithWhereWithoutOrgInput = {
  where: Prisma.MessageParticipantScalarWhereInput
  data: Prisma.XOR<Prisma.MessageParticipantUpdateManyMutationInput, Prisma.MessageParticipantUncheckedUpdateManyWithoutOrgInput>
}

export type MessageParticipantScalarWhereInput = {
  AND?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
  OR?: Prisma.MessageParticipantScalarWhereInput[]
  NOT?: Prisma.MessageParticipantScalarWhereInput | Prisma.MessageParticipantScalarWhereInput[]
  id?: Prisma.UuidFilter<"MessageParticipant"> | string
  orgId?: Prisma.UuidFilter<"MessageParticipant"> | string
  userId?: Prisma.UuidFilter<"MessageParticipant"> | string
  messageId?: Prisma.UuidFilter<"MessageParticipant"> | string
  contactId?: Prisma.UuidNullableFilter<"MessageParticipant"> | string | null
  handle?: Prisma.StringFilter<"MessageParticipant"> | string
  displayName?: Prisma.StringNullableFilter<"MessageParticipant"> | string | null
  role?: Prisma.StringFilter<"MessageParticipant"> | string
  createdAt?: Prisma.DateTimeFilter<"MessageParticipant"> | Date | string
}

export type MessageParticipantCreateWithoutUserInput = {
  id?: string
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutMessageParticipantsInput
  message: Prisma.MessageCreateNestedOneWithoutParticipantsInput
  contact?: Prisma.ContactCreateNestedOneWithoutMessageParticipantsInput
}

export type MessageParticipantUncheckedCreateWithoutUserInput = {
  id?: string
  orgId: string
  messageId: string
  contactId?: string | null
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantCreateOrConnectWithoutUserInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageParticipantCreateWithoutUserInput, Prisma.MessageParticipantUncheckedCreateWithoutUserInput>
}

export type MessageParticipantCreateManyUserInputEnvelope = {
  data: Prisma.MessageParticipantCreateManyUserInput | Prisma.MessageParticipantCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type MessageParticipantUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageParticipantUpdateWithoutUserInput, Prisma.MessageParticipantUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.MessageParticipantCreateWithoutUserInput, Prisma.MessageParticipantUncheckedCreateWithoutUserInput>
}

export type MessageParticipantUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageParticipantUpdateWithoutUserInput, Prisma.MessageParticipantUncheckedUpdateWithoutUserInput>
}

export type MessageParticipantUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.MessageParticipantScalarWhereInput
  data: Prisma.XOR<Prisma.MessageParticipantUpdateManyMutationInput, Prisma.MessageParticipantUncheckedUpdateManyWithoutUserInput>
}

export type MessageParticipantCreateWithoutContactInput = {
  id?: string
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutMessageParticipantsInput
  user: Prisma.UserCreateNestedOneWithoutMessageParticipantsInput
  message: Prisma.MessageCreateNestedOneWithoutParticipantsInput
}

export type MessageParticipantUncheckedCreateWithoutContactInput = {
  id?: string
  orgId: string
  userId: string
  messageId: string
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantCreateOrConnectWithoutContactInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageParticipantCreateWithoutContactInput, Prisma.MessageParticipantUncheckedCreateWithoutContactInput>
}

export type MessageParticipantCreateManyContactInputEnvelope = {
  data: Prisma.MessageParticipantCreateManyContactInput | Prisma.MessageParticipantCreateManyContactInput[]
  skipDuplicates?: boolean
}

export type MessageParticipantUpsertWithWhereUniqueWithoutContactInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageParticipantUpdateWithoutContactInput, Prisma.MessageParticipantUncheckedUpdateWithoutContactInput>
  create: Prisma.XOR<Prisma.MessageParticipantCreateWithoutContactInput, Prisma.MessageParticipantUncheckedCreateWithoutContactInput>
}

export type MessageParticipantUpdateWithWhereUniqueWithoutContactInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageParticipantUpdateWithoutContactInput, Prisma.MessageParticipantUncheckedUpdateWithoutContactInput>
}

export type MessageParticipantUpdateManyWithWhereWithoutContactInput = {
  where: Prisma.MessageParticipantScalarWhereInput
  data: Prisma.XOR<Prisma.MessageParticipantUpdateManyMutationInput, Prisma.MessageParticipantUncheckedUpdateManyWithoutContactInput>
}

export type MessageParticipantCreateWithoutMessageInput = {
  id?: string
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutMessageParticipantsInput
  user: Prisma.UserCreateNestedOneWithoutMessageParticipantsInput
  contact?: Prisma.ContactCreateNestedOneWithoutMessageParticipantsInput
}

export type MessageParticipantUncheckedCreateWithoutMessageInput = {
  id?: string
  orgId: string
  userId: string
  contactId?: string | null
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantCreateOrConnectWithoutMessageInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageParticipantCreateWithoutMessageInput, Prisma.MessageParticipantUncheckedCreateWithoutMessageInput>
}

export type MessageParticipantCreateManyMessageInputEnvelope = {
  data: Prisma.MessageParticipantCreateManyMessageInput | Prisma.MessageParticipantCreateManyMessageInput[]
  skipDuplicates?: boolean
}

export type MessageParticipantUpsertWithWhereUniqueWithoutMessageInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageParticipantUpdateWithoutMessageInput, Prisma.MessageParticipantUncheckedUpdateWithoutMessageInput>
  create: Prisma.XOR<Prisma.MessageParticipantCreateWithoutMessageInput, Prisma.MessageParticipantUncheckedCreateWithoutMessageInput>
}

export type MessageParticipantUpdateWithWhereUniqueWithoutMessageInput = {
  where: Prisma.MessageParticipantWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageParticipantUpdateWithoutMessageInput, Prisma.MessageParticipantUncheckedUpdateWithoutMessageInput>
}

export type MessageParticipantUpdateManyWithWhereWithoutMessageInput = {
  where: Prisma.MessageParticipantScalarWhereInput
  data: Prisma.XOR<Prisma.MessageParticipantUpdateManyMutationInput, Prisma.MessageParticipantUncheckedUpdateManyWithoutMessageInput>
}

export type MessageParticipantCreateManyOrgInput = {
  id?: string
  userId: string
  messageId: string
  contactId?: string | null
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutMessageParticipantsNestedInput
  message?: Prisma.MessageUpdateOneRequiredWithoutParticipantsNestedInput
  contact?: Prisma.ContactUpdateOneWithoutMessageParticipantsNestedInput
}

export type MessageParticipantUncheckedUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantUncheckedUpdateManyWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantCreateManyUserInput = {
  id?: string
  orgId: string
  messageId: string
  contactId?: string | null
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutMessageParticipantsNestedInput
  message?: Prisma.MessageUpdateOneRequiredWithoutParticipantsNestedInput
  contact?: Prisma.ContactUpdateOneWithoutMessageParticipantsNestedInput
}

export type MessageParticipantUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantCreateManyContactInput = {
  id?: string
  orgId: string
  userId: string
  messageId: string
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantUpdateWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutMessageParticipantsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutMessageParticipantsNestedInput
  message?: Prisma.MessageUpdateOneRequiredWithoutParticipantsNestedInput
}

export type MessageParticipantUncheckedUpdateWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantUncheckedUpdateManyWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantCreateManyMessageInput = {
  id?: string
  orgId: string
  userId: string
  contactId?: string | null
  handle: string
  displayName?: string | null
  role: string
  createdAt?: Date | string
}

export type MessageParticipantUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutMessageParticipantsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutMessageParticipantsNestedInput
  contact?: Prisma.ContactUpdateOneWithoutMessageParticipantsNestedInput
}

export type MessageParticipantUncheckedUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageParticipantUncheckedUpdateManyWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MessageParticipantSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orgId?: boolean
  userId?: boolean
  messageId?: boolean
  contactId?: boolean
  handle?: boolean
  displayName?: boolean
  role?: boolean
  createdAt?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.MessageParticipant$contactArgs<ExtArgs>
}, ExtArgs["result"]["messageParticipant"]>

export type MessageParticipantSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orgId?: boolean
  userId?: boolean
  messageId?: boolean
  contactId?: boolean
  handle?: boolean
  displayName?: boolean
  role?: boolean
  createdAt?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.MessageParticipant$contactArgs<ExtArgs>
}, ExtArgs["result"]["messageParticipant"]>

export type MessageParticipantSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orgId?: boolean
  userId?: boolean
  messageId?: boolean
  contactId?: boolean
  handle?: boolean
  displayName?: boolean
  role?: boolean
  createdAt?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.MessageParticipant$contactArgs<ExtArgs>
}, ExtArgs["result"]["messageParticipant"]>

export type MessageParticipantSelectScalar = {
  id?: boolean
  orgId?: boolean
  userId?: boolean
  messageId?: boolean
  contactId?: boolean
  handle?: boolean
  displayName?: boolean
  role?: boolean
  createdAt?: boolean
}

export type MessageParticipantOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orgId" | "userId" | "messageId" | "contactId" | "handle" | "displayName" | "role" | "createdAt", ExtArgs["result"]["messageParticipant"]>
export type MessageParticipantInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.MessageParticipant$contactArgs<ExtArgs>
}
export type MessageParticipantIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.MessageParticipant$contactArgs<ExtArgs>
}
export type MessageParticipantIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.MessageParticipant$contactArgs<ExtArgs>
}

export type $MessageParticipantPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MessageParticipant"
  objects: {
    org: Prisma.$OrgPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    message: Prisma.$MessagePayload<ExtArgs>
    contact: Prisma.$ContactPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orgId: string
    userId: string
    messageId: string
    contactId: string | null
    handle: string
    displayName: string | null
    role: string
    createdAt: Date
  }, ExtArgs["result"]["messageParticipant"]>
  composites: {}
}

export type MessageParticipantGetPayload<S extends boolean | null | undefined | MessageParticipantDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload, S>

export type MessageParticipantCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MessageParticipantFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MessageParticipantCountAggregateInputType | true
  }

export interface MessageParticipantDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MessageParticipant'], meta: { name: 'MessageParticipant' } }
  /**
   * Find zero or one MessageParticipant that matches the filter.
   * @param {MessageParticipantFindUniqueArgs} args - Arguments to find a MessageParticipant
   * @example
   * // Get one MessageParticipant
   * const messageParticipant = await prisma.messageParticipant.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MessageParticipantFindUniqueArgs>(args: Prisma.SelectSubset<T, MessageParticipantFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MessageParticipantClient<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MessageParticipant that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MessageParticipantFindUniqueOrThrowArgs} args - Arguments to find a MessageParticipant
   * @example
   * // Get one MessageParticipant
   * const messageParticipant = await prisma.messageParticipant.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MessageParticipantFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MessageParticipantFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageParticipantClient<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MessageParticipant that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageParticipantFindFirstArgs} args - Arguments to find a MessageParticipant
   * @example
   * // Get one MessageParticipant
   * const messageParticipant = await prisma.messageParticipant.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MessageParticipantFindFirstArgs>(args?: Prisma.SelectSubset<T, MessageParticipantFindFirstArgs<ExtArgs>>): Prisma.Prisma__MessageParticipantClient<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MessageParticipant that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageParticipantFindFirstOrThrowArgs} args - Arguments to find a MessageParticipant
   * @example
   * // Get one MessageParticipant
   * const messageParticipant = await prisma.messageParticipant.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MessageParticipantFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MessageParticipantFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageParticipantClient<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MessageParticipants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageParticipantFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MessageParticipants
   * const messageParticipants = await prisma.messageParticipant.findMany()
   * 
   * // Get first 10 MessageParticipants
   * const messageParticipants = await prisma.messageParticipant.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const messageParticipantWithIdOnly = await prisma.messageParticipant.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MessageParticipantFindManyArgs>(args?: Prisma.SelectSubset<T, MessageParticipantFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MessageParticipant.
   * @param {MessageParticipantCreateArgs} args - Arguments to create a MessageParticipant.
   * @example
   * // Create one MessageParticipant
   * const MessageParticipant = await prisma.messageParticipant.create({
   *   data: {
   *     // ... data to create a MessageParticipant
   *   }
   * })
   * 
   */
  create<T extends MessageParticipantCreateArgs>(args: Prisma.SelectSubset<T, MessageParticipantCreateArgs<ExtArgs>>): Prisma.Prisma__MessageParticipantClient<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MessageParticipants.
   * @param {MessageParticipantCreateManyArgs} args - Arguments to create many MessageParticipants.
   * @example
   * // Create many MessageParticipants
   * const messageParticipant = await prisma.messageParticipant.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MessageParticipantCreateManyArgs>(args?: Prisma.SelectSubset<T, MessageParticipantCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MessageParticipants and returns the data saved in the database.
   * @param {MessageParticipantCreateManyAndReturnArgs} args - Arguments to create many MessageParticipants.
   * @example
   * // Create many MessageParticipants
   * const messageParticipant = await prisma.messageParticipant.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MessageParticipants and only return the `id`
   * const messageParticipantWithIdOnly = await prisma.messageParticipant.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MessageParticipantCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MessageParticipantCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MessageParticipant.
   * @param {MessageParticipantDeleteArgs} args - Arguments to delete one MessageParticipant.
   * @example
   * // Delete one MessageParticipant
   * const MessageParticipant = await prisma.messageParticipant.delete({
   *   where: {
   *     // ... filter to delete one MessageParticipant
   *   }
   * })
   * 
   */
  delete<T extends MessageParticipantDeleteArgs>(args: Prisma.SelectSubset<T, MessageParticipantDeleteArgs<ExtArgs>>): Prisma.Prisma__MessageParticipantClient<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MessageParticipant.
   * @param {MessageParticipantUpdateArgs} args - Arguments to update one MessageParticipant.
   * @example
   * // Update one MessageParticipant
   * const messageParticipant = await prisma.messageParticipant.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MessageParticipantUpdateArgs>(args: Prisma.SelectSubset<T, MessageParticipantUpdateArgs<ExtArgs>>): Prisma.Prisma__MessageParticipantClient<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MessageParticipants.
   * @param {MessageParticipantDeleteManyArgs} args - Arguments to filter MessageParticipants to delete.
   * @example
   * // Delete a few MessageParticipants
   * const { count } = await prisma.messageParticipant.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MessageParticipantDeleteManyArgs>(args?: Prisma.SelectSubset<T, MessageParticipantDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MessageParticipants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageParticipantUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MessageParticipants
   * const messageParticipant = await prisma.messageParticipant.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MessageParticipantUpdateManyArgs>(args: Prisma.SelectSubset<T, MessageParticipantUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MessageParticipants and returns the data updated in the database.
   * @param {MessageParticipantUpdateManyAndReturnArgs} args - Arguments to update many MessageParticipants.
   * @example
   * // Update many MessageParticipants
   * const messageParticipant = await prisma.messageParticipant.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MessageParticipants and only return the `id`
   * const messageParticipantWithIdOnly = await prisma.messageParticipant.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MessageParticipantUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MessageParticipantUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MessageParticipant.
   * @param {MessageParticipantUpsertArgs} args - Arguments to update or create a MessageParticipant.
   * @example
   * // Update or create a MessageParticipant
   * const messageParticipant = await prisma.messageParticipant.upsert({
   *   create: {
   *     // ... data to create a MessageParticipant
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MessageParticipant we want to update
   *   }
   * })
   */
  upsert<T extends MessageParticipantUpsertArgs>(args: Prisma.SelectSubset<T, MessageParticipantUpsertArgs<ExtArgs>>): Prisma.Prisma__MessageParticipantClient<runtime.Types.Result.GetResult<Prisma.$MessageParticipantPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MessageParticipants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageParticipantCountArgs} args - Arguments to filter MessageParticipants to count.
   * @example
   * // Count the number of MessageParticipants
   * const count = await prisma.messageParticipant.count({
   *   where: {
   *     // ... the filter for the MessageParticipants we want to count
   *   }
   * })
  **/
  count<T extends MessageParticipantCountArgs>(
    args?: Prisma.Subset<T, MessageParticipantCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MessageParticipantCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MessageParticipant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageParticipantAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MessageParticipantAggregateArgs>(args: Prisma.Subset<T, MessageParticipantAggregateArgs>): Prisma.PrismaPromise<GetMessageParticipantAggregateType<T>>

  /**
   * Group by MessageParticipant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageParticipantGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MessageParticipantGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MessageParticipantGroupByArgs['orderBy'] }
      : { orderBy?: MessageParticipantGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MessageParticipantGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMessageParticipantGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MessageParticipant model
 */
readonly fields: MessageParticipantFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MessageParticipant.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MessageParticipantClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  org<T extends Prisma.OrgDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrgDefaultArgs<ExtArgs>>): Prisma.Prisma__OrgClient<runtime.Types.Result.GetResult<Prisma.$OrgPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  message<T extends Prisma.MessageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MessageDefaultArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  contact<T extends Prisma.MessageParticipant$contactArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MessageParticipant$contactArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MessageParticipant model
 */
export interface MessageParticipantFieldRefs {
  readonly id: Prisma.FieldRef<"MessageParticipant", 'String'>
  readonly orgId: Prisma.FieldRef<"MessageParticipant", 'String'>
  readonly userId: Prisma.FieldRef<"MessageParticipant", 'String'>
  readonly messageId: Prisma.FieldRef<"MessageParticipant", 'String'>
  readonly contactId: Prisma.FieldRef<"MessageParticipant", 'String'>
  readonly handle: Prisma.FieldRef<"MessageParticipant", 'String'>
  readonly displayName: Prisma.FieldRef<"MessageParticipant", 'String'>
  readonly role: Prisma.FieldRef<"MessageParticipant", 'String'>
  readonly createdAt: Prisma.FieldRef<"MessageParticipant", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MessageParticipant findUnique
 */
export type MessageParticipantFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
  /**
   * Filter, which MessageParticipant to fetch.
   */
  where: Prisma.MessageParticipantWhereUniqueInput
}

/**
 * MessageParticipant findUniqueOrThrow
 */
export type MessageParticipantFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
  /**
   * Filter, which MessageParticipant to fetch.
   */
  where: Prisma.MessageParticipantWhereUniqueInput
}

/**
 * MessageParticipant findFirst
 */
export type MessageParticipantFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
  /**
   * Filter, which MessageParticipant to fetch.
   */
  where?: Prisma.MessageParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageParticipants to fetch.
   */
  orderBy?: Prisma.MessageParticipantOrderByWithRelationInput | Prisma.MessageParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MessageParticipants.
   */
  cursor?: Prisma.MessageParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageParticipants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageParticipants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MessageParticipants.
   */
  distinct?: Prisma.MessageParticipantScalarFieldEnum | Prisma.MessageParticipantScalarFieldEnum[]
}

/**
 * MessageParticipant findFirstOrThrow
 */
export type MessageParticipantFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
  /**
   * Filter, which MessageParticipant to fetch.
   */
  where?: Prisma.MessageParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageParticipants to fetch.
   */
  orderBy?: Prisma.MessageParticipantOrderByWithRelationInput | Prisma.MessageParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MessageParticipants.
   */
  cursor?: Prisma.MessageParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageParticipants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageParticipants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MessageParticipants.
   */
  distinct?: Prisma.MessageParticipantScalarFieldEnum | Prisma.MessageParticipantScalarFieldEnum[]
}

/**
 * MessageParticipant findMany
 */
export type MessageParticipantFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
  /**
   * Filter, which MessageParticipants to fetch.
   */
  where?: Prisma.MessageParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageParticipants to fetch.
   */
  orderBy?: Prisma.MessageParticipantOrderByWithRelationInput | Prisma.MessageParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MessageParticipants.
   */
  cursor?: Prisma.MessageParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageParticipants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageParticipants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MessageParticipants.
   */
  distinct?: Prisma.MessageParticipantScalarFieldEnum | Prisma.MessageParticipantScalarFieldEnum[]
}

/**
 * MessageParticipant create
 */
export type MessageParticipantCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
  /**
   * The data needed to create a MessageParticipant.
   */
  data: Prisma.XOR<Prisma.MessageParticipantCreateInput, Prisma.MessageParticipantUncheckedCreateInput>
}

/**
 * MessageParticipant createMany
 */
export type MessageParticipantCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MessageParticipants.
   */
  data: Prisma.MessageParticipantCreateManyInput | Prisma.MessageParticipantCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MessageParticipant createManyAndReturn
 */
export type MessageParticipantCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * The data used to create many MessageParticipants.
   */
  data: Prisma.MessageParticipantCreateManyInput | Prisma.MessageParticipantCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MessageParticipant update
 */
export type MessageParticipantUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
  /**
   * The data needed to update a MessageParticipant.
   */
  data: Prisma.XOR<Prisma.MessageParticipantUpdateInput, Prisma.MessageParticipantUncheckedUpdateInput>
  /**
   * Choose, which MessageParticipant to update.
   */
  where: Prisma.MessageParticipantWhereUniqueInput
}

/**
 * MessageParticipant updateMany
 */
export type MessageParticipantUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MessageParticipants.
   */
  data: Prisma.XOR<Prisma.MessageParticipantUpdateManyMutationInput, Prisma.MessageParticipantUncheckedUpdateManyInput>
  /**
   * Filter which MessageParticipants to update
   */
  where?: Prisma.MessageParticipantWhereInput
  /**
   * Limit how many MessageParticipants to update.
   */
  limit?: number
}

/**
 * MessageParticipant updateManyAndReturn
 */
export type MessageParticipantUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * The data used to update MessageParticipants.
   */
  data: Prisma.XOR<Prisma.MessageParticipantUpdateManyMutationInput, Prisma.MessageParticipantUncheckedUpdateManyInput>
  /**
   * Filter which MessageParticipants to update
   */
  where?: Prisma.MessageParticipantWhereInput
  /**
   * Limit how many MessageParticipants to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MessageParticipant upsert
 */
export type MessageParticipantUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
  /**
   * The filter to search for the MessageParticipant to update in case it exists.
   */
  where: Prisma.MessageParticipantWhereUniqueInput
  /**
   * In case the MessageParticipant found by the `where` argument doesn't exist, create a new MessageParticipant with this data.
   */
  create: Prisma.XOR<Prisma.MessageParticipantCreateInput, Prisma.MessageParticipantUncheckedCreateInput>
  /**
   * In case the MessageParticipant was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MessageParticipantUpdateInput, Prisma.MessageParticipantUncheckedUpdateInput>
}

/**
 * MessageParticipant delete
 */
export type MessageParticipantDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
  /**
   * Filter which MessageParticipant to delete.
   */
  where: Prisma.MessageParticipantWhereUniqueInput
}

/**
 * MessageParticipant deleteMany
 */
export type MessageParticipantDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MessageParticipants to delete
   */
  where?: Prisma.MessageParticipantWhereInput
  /**
   * Limit how many MessageParticipants to delete.
   */
  limit?: number
}

/**
 * MessageParticipant.contact
 */
export type MessageParticipant$contactArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  where?: Prisma.ContactWhereInput
}

/**
 * MessageParticipant without action
 */
export type MessageParticipantDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageParticipant
   */
  select?: Prisma.MessageParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageParticipant
   */
  omit?: Prisma.MessageParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageParticipantInclude<ExtArgs> | null
}
