
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SyncTask` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SyncTask
 * 
 */
export type SyncTaskModel = runtime.Types.Result.DefaultSelection<Prisma.$SyncTaskPayload>

export type AggregateSyncTask = {
  _count: SyncTaskCountAggregateOutputType | null
  _min: SyncTaskMinAggregateOutputType | null
  _max: SyncTaskMaxAggregateOutputType | null
}

export type SyncTaskMinAggregateOutputType = {
  id: string | null
  orgId: string | null
  userId: string | null
  jobId: string | null
  providerAccountId: string | null
  createdAt: Date | null
}

export type SyncTaskMaxAggregateOutputType = {
  id: string | null
  orgId: string | null
  userId: string | null
  jobId: string | null
  providerAccountId: string | null
  createdAt: Date | null
}

export type SyncTaskCountAggregateOutputType = {
  id: number
  orgId: number
  userId: number
  jobId: number
  providerAccountId: number
  spec: number
  createdAt: number
  _all: number
}


export type SyncTaskMinAggregateInputType = {
  id?: true
  orgId?: true
  userId?: true
  jobId?: true
  providerAccountId?: true
  createdAt?: true
}

export type SyncTaskMaxAggregateInputType = {
  id?: true
  orgId?: true
  userId?: true
  jobId?: true
  providerAccountId?: true
  createdAt?: true
}

export type SyncTaskCountAggregateInputType = {
  id?: true
  orgId?: true
  userId?: true
  jobId?: true
  providerAccountId?: true
  spec?: true
  createdAt?: true
  _all?: true
}

export type SyncTaskAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SyncTask to aggregate.
   */
  where?: Prisma.SyncTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncTasks to fetch.
   */
  orderBy?: Prisma.SyncTaskOrderByWithRelationInput | Prisma.SyncTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SyncTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SyncTasks
  **/
  _count?: true | SyncTaskCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SyncTaskMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SyncTaskMaxAggregateInputType
}

export type GetSyncTaskAggregateType<T extends SyncTaskAggregateArgs> = {
      [P in keyof T & keyof AggregateSyncTask]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSyncTask[P]>
    : Prisma.GetScalarType<T[P], AggregateSyncTask[P]>
}




export type SyncTaskGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SyncTaskWhereInput
  orderBy?: Prisma.SyncTaskOrderByWithAggregationInput | Prisma.SyncTaskOrderByWithAggregationInput[]
  by: Prisma.SyncTaskScalarFieldEnum[] | Prisma.SyncTaskScalarFieldEnum
  having?: Prisma.SyncTaskScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SyncTaskCountAggregateInputType | true
  _min?: SyncTaskMinAggregateInputType
  _max?: SyncTaskMaxAggregateInputType
}

export type SyncTaskGroupByOutputType = {
  id: string
  orgId: string
  userId: string
  jobId: string
  providerAccountId: string
  spec: runtime.JsonValue
  createdAt: Date
  _count: SyncTaskCountAggregateOutputType | null
  _min: SyncTaskMinAggregateOutputType | null
  _max: SyncTaskMaxAggregateOutputType | null
}

export type GetSyncTaskGroupByPayload<T extends SyncTaskGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SyncTaskGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SyncTaskGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SyncTaskGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SyncTaskGroupByOutputType[P]>
      }
    >
  >



export type SyncTaskWhereInput = {
  AND?: Prisma.SyncTaskWhereInput | Prisma.SyncTaskWhereInput[]
  OR?: Prisma.SyncTaskWhereInput[]
  NOT?: Prisma.SyncTaskWhereInput | Prisma.SyncTaskWhereInput[]
  id?: Prisma.UuidFilter<"SyncTask"> | string
  orgId?: Prisma.UuidFilter<"SyncTask"> | string
  userId?: Prisma.UuidFilter<"SyncTask"> | string
  jobId?: Prisma.UuidFilter<"SyncTask"> | string
  providerAccountId?: Prisma.UuidFilter<"SyncTask"> | string
  spec?: Prisma.JsonFilter<"SyncTask">
  createdAt?: Prisma.DateTimeFilter<"SyncTask"> | Date | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  job?: Prisma.XOR<Prisma.SyncJobScalarRelationFilter, Prisma.SyncJobWhereInput>
  providerAccount?: Prisma.XOR<Prisma.ProviderAccountScalarRelationFilter, Prisma.ProviderAccountWhereInput>
  events?: Prisma.SyncTaskEventListRelationFilter
  messageRaws?: Prisma.MessageRawListRelationFilter
}

export type SyncTaskOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
  spec?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  org?: Prisma.OrgOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  job?: Prisma.SyncJobOrderByWithRelationInput
  providerAccount?: Prisma.ProviderAccountOrderByWithRelationInput
  events?: Prisma.SyncTaskEventOrderByRelationAggregateInput
  messageRaws?: Prisma.MessageRawOrderByRelationAggregateInput
}

export type SyncTaskWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SyncTaskWhereInput | Prisma.SyncTaskWhereInput[]
  OR?: Prisma.SyncTaskWhereInput[]
  NOT?: Prisma.SyncTaskWhereInput | Prisma.SyncTaskWhereInput[]
  orgId?: Prisma.UuidFilter<"SyncTask"> | string
  userId?: Prisma.UuidFilter<"SyncTask"> | string
  jobId?: Prisma.UuidFilter<"SyncTask"> | string
  providerAccountId?: Prisma.UuidFilter<"SyncTask"> | string
  spec?: Prisma.JsonFilter<"SyncTask">
  createdAt?: Prisma.DateTimeFilter<"SyncTask"> | Date | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  job?: Prisma.XOR<Prisma.SyncJobScalarRelationFilter, Prisma.SyncJobWhereInput>
  providerAccount?: Prisma.XOR<Prisma.ProviderAccountScalarRelationFilter, Prisma.ProviderAccountWhereInput>
  events?: Prisma.SyncTaskEventListRelationFilter
  messageRaws?: Prisma.MessageRawListRelationFilter
}, "id">

export type SyncTaskOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
  spec?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.SyncTaskCountOrderByAggregateInput
  _max?: Prisma.SyncTaskMaxOrderByAggregateInput
  _min?: Prisma.SyncTaskMinOrderByAggregateInput
}

export type SyncTaskScalarWhereWithAggregatesInput = {
  AND?: Prisma.SyncTaskScalarWhereWithAggregatesInput | Prisma.SyncTaskScalarWhereWithAggregatesInput[]
  OR?: Prisma.SyncTaskScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SyncTaskScalarWhereWithAggregatesInput | Prisma.SyncTaskScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"SyncTask"> | string
  orgId?: Prisma.UuidWithAggregatesFilter<"SyncTask"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"SyncTask"> | string
  jobId?: Prisma.UuidWithAggregatesFilter<"SyncTask"> | string
  providerAccountId?: Prisma.UuidWithAggregatesFilter<"SyncTask"> | string
  spec?: Prisma.JsonWithAggregatesFilter<"SyncTask">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SyncTask"> | Date | string
}

export type SyncTaskCreateInput = {
  id?: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutSyncTasksInput
  user: Prisma.UserCreateNestedOneWithoutSyncTasksInput
  job: Prisma.SyncJobCreateNestedOneWithoutTasksInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutSyncTasksInput
  events?: Prisma.SyncTaskEventCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskUncheckedCreateInput = {
  id?: string
  orgId: string
  userId: string
  jobId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  events?: Prisma.SyncTaskEventUncheckedCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawUncheckedCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutSyncTasksNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutSyncTasksNestedInput
  job?: Prisma.SyncJobUpdateOneRequiredWithoutTasksNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutSyncTasksNestedInput
  events?: Prisma.SyncTaskEventUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.SyncTaskEventUncheckedUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUncheckedUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskCreateManyInput = {
  id?: string
  orgId: string
  userId: string
  jobId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type SyncTaskUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncTaskUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncTaskListRelationFilter = {
  every?: Prisma.SyncTaskWhereInput
  some?: Prisma.SyncTaskWhereInput
  none?: Prisma.SyncTaskWhereInput
}

export type SyncTaskOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SyncTaskScalarRelationFilter = {
  is?: Prisma.SyncTaskWhereInput
  isNot?: Prisma.SyncTaskWhereInput
}

export type SyncTaskCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
  spec?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SyncTaskMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SyncTaskMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SyncTaskCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutOrgInput, Prisma.SyncTaskUncheckedCreateWithoutOrgInput> | Prisma.SyncTaskCreateWithoutOrgInput[] | Prisma.SyncTaskUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutOrgInput | Prisma.SyncTaskCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.SyncTaskCreateManyOrgInputEnvelope
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
}

export type SyncTaskUncheckedCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutOrgInput, Prisma.SyncTaskUncheckedCreateWithoutOrgInput> | Prisma.SyncTaskCreateWithoutOrgInput[] | Prisma.SyncTaskUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutOrgInput | Prisma.SyncTaskCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.SyncTaskCreateManyOrgInputEnvelope
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
}

export type SyncTaskUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutOrgInput, Prisma.SyncTaskUncheckedCreateWithoutOrgInput> | Prisma.SyncTaskCreateWithoutOrgInput[] | Prisma.SyncTaskUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutOrgInput | Prisma.SyncTaskCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.SyncTaskUpsertWithWhereUniqueWithoutOrgInput | Prisma.SyncTaskUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.SyncTaskCreateManyOrgInputEnvelope
  set?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  disconnect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  delete?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  update?: Prisma.SyncTaskUpdateWithWhereUniqueWithoutOrgInput | Prisma.SyncTaskUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.SyncTaskUpdateManyWithWhereWithoutOrgInput | Prisma.SyncTaskUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
}

export type SyncTaskUncheckedUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutOrgInput, Prisma.SyncTaskUncheckedCreateWithoutOrgInput> | Prisma.SyncTaskCreateWithoutOrgInput[] | Prisma.SyncTaskUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutOrgInput | Prisma.SyncTaskCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.SyncTaskUpsertWithWhereUniqueWithoutOrgInput | Prisma.SyncTaskUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.SyncTaskCreateManyOrgInputEnvelope
  set?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  disconnect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  delete?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  update?: Prisma.SyncTaskUpdateWithWhereUniqueWithoutOrgInput | Prisma.SyncTaskUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.SyncTaskUpdateManyWithWhereWithoutOrgInput | Prisma.SyncTaskUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
}

export type SyncTaskCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutUserInput, Prisma.SyncTaskUncheckedCreateWithoutUserInput> | Prisma.SyncTaskCreateWithoutUserInput[] | Prisma.SyncTaskUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutUserInput | Prisma.SyncTaskCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SyncTaskCreateManyUserInputEnvelope
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
}

export type SyncTaskUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutUserInput, Prisma.SyncTaskUncheckedCreateWithoutUserInput> | Prisma.SyncTaskCreateWithoutUserInput[] | Prisma.SyncTaskUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutUserInput | Prisma.SyncTaskCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SyncTaskCreateManyUserInputEnvelope
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
}

export type SyncTaskUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutUserInput, Prisma.SyncTaskUncheckedCreateWithoutUserInput> | Prisma.SyncTaskCreateWithoutUserInput[] | Prisma.SyncTaskUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutUserInput | Prisma.SyncTaskCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SyncTaskUpsertWithWhereUniqueWithoutUserInput | Prisma.SyncTaskUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SyncTaskCreateManyUserInputEnvelope
  set?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  disconnect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  delete?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  update?: Prisma.SyncTaskUpdateWithWhereUniqueWithoutUserInput | Prisma.SyncTaskUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SyncTaskUpdateManyWithWhereWithoutUserInput | Prisma.SyncTaskUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
}

export type SyncTaskUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutUserInput, Prisma.SyncTaskUncheckedCreateWithoutUserInput> | Prisma.SyncTaskCreateWithoutUserInput[] | Prisma.SyncTaskUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutUserInput | Prisma.SyncTaskCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SyncTaskUpsertWithWhereUniqueWithoutUserInput | Prisma.SyncTaskUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SyncTaskCreateManyUserInputEnvelope
  set?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  disconnect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  delete?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  update?: Prisma.SyncTaskUpdateWithWhereUniqueWithoutUserInput | Prisma.SyncTaskUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SyncTaskUpdateManyWithWhereWithoutUserInput | Prisma.SyncTaskUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
}

export type SyncTaskCreateNestedManyWithoutProviderAccountInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutProviderAccountInput, Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput> | Prisma.SyncTaskCreateWithoutProviderAccountInput[] | Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutProviderAccountInput | Prisma.SyncTaskCreateOrConnectWithoutProviderAccountInput[]
  createMany?: Prisma.SyncTaskCreateManyProviderAccountInputEnvelope
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
}

export type SyncTaskUncheckedCreateNestedManyWithoutProviderAccountInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutProviderAccountInput, Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput> | Prisma.SyncTaskCreateWithoutProviderAccountInput[] | Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutProviderAccountInput | Prisma.SyncTaskCreateOrConnectWithoutProviderAccountInput[]
  createMany?: Prisma.SyncTaskCreateManyProviderAccountInputEnvelope
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
}

export type SyncTaskUpdateManyWithoutProviderAccountNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutProviderAccountInput, Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput> | Prisma.SyncTaskCreateWithoutProviderAccountInput[] | Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutProviderAccountInput | Prisma.SyncTaskCreateOrConnectWithoutProviderAccountInput[]
  upsert?: Prisma.SyncTaskUpsertWithWhereUniqueWithoutProviderAccountInput | Prisma.SyncTaskUpsertWithWhereUniqueWithoutProviderAccountInput[]
  createMany?: Prisma.SyncTaskCreateManyProviderAccountInputEnvelope
  set?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  disconnect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  delete?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  update?: Prisma.SyncTaskUpdateWithWhereUniqueWithoutProviderAccountInput | Prisma.SyncTaskUpdateWithWhereUniqueWithoutProviderAccountInput[]
  updateMany?: Prisma.SyncTaskUpdateManyWithWhereWithoutProviderAccountInput | Prisma.SyncTaskUpdateManyWithWhereWithoutProviderAccountInput[]
  deleteMany?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
}

export type SyncTaskUncheckedUpdateManyWithoutProviderAccountNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutProviderAccountInput, Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput> | Prisma.SyncTaskCreateWithoutProviderAccountInput[] | Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutProviderAccountInput | Prisma.SyncTaskCreateOrConnectWithoutProviderAccountInput[]
  upsert?: Prisma.SyncTaskUpsertWithWhereUniqueWithoutProviderAccountInput | Prisma.SyncTaskUpsertWithWhereUniqueWithoutProviderAccountInput[]
  createMany?: Prisma.SyncTaskCreateManyProviderAccountInputEnvelope
  set?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  disconnect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  delete?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  update?: Prisma.SyncTaskUpdateWithWhereUniqueWithoutProviderAccountInput | Prisma.SyncTaskUpdateWithWhereUniqueWithoutProviderAccountInput[]
  updateMany?: Prisma.SyncTaskUpdateManyWithWhereWithoutProviderAccountInput | Prisma.SyncTaskUpdateManyWithWhereWithoutProviderAccountInput[]
  deleteMany?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
}

export type SyncTaskCreateNestedOneWithoutMessageRawsInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutMessageRawsInput, Prisma.SyncTaskUncheckedCreateWithoutMessageRawsInput>
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutMessageRawsInput
  connect?: Prisma.SyncTaskWhereUniqueInput
}

export type SyncTaskUpdateOneRequiredWithoutMessageRawsNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutMessageRawsInput, Prisma.SyncTaskUncheckedCreateWithoutMessageRawsInput>
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutMessageRawsInput
  upsert?: Prisma.SyncTaskUpsertWithoutMessageRawsInput
  connect?: Prisma.SyncTaskWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SyncTaskUpdateToOneWithWhereWithoutMessageRawsInput, Prisma.SyncTaskUpdateWithoutMessageRawsInput>, Prisma.SyncTaskUncheckedUpdateWithoutMessageRawsInput>
}

export type SyncTaskCreateNestedManyWithoutJobInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutJobInput, Prisma.SyncTaskUncheckedCreateWithoutJobInput> | Prisma.SyncTaskCreateWithoutJobInput[] | Prisma.SyncTaskUncheckedCreateWithoutJobInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutJobInput | Prisma.SyncTaskCreateOrConnectWithoutJobInput[]
  createMany?: Prisma.SyncTaskCreateManyJobInputEnvelope
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
}

export type SyncTaskUncheckedCreateNestedManyWithoutJobInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutJobInput, Prisma.SyncTaskUncheckedCreateWithoutJobInput> | Prisma.SyncTaskCreateWithoutJobInput[] | Prisma.SyncTaskUncheckedCreateWithoutJobInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutJobInput | Prisma.SyncTaskCreateOrConnectWithoutJobInput[]
  createMany?: Prisma.SyncTaskCreateManyJobInputEnvelope
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
}

export type SyncTaskUpdateManyWithoutJobNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutJobInput, Prisma.SyncTaskUncheckedCreateWithoutJobInput> | Prisma.SyncTaskCreateWithoutJobInput[] | Prisma.SyncTaskUncheckedCreateWithoutJobInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutJobInput | Prisma.SyncTaskCreateOrConnectWithoutJobInput[]
  upsert?: Prisma.SyncTaskUpsertWithWhereUniqueWithoutJobInput | Prisma.SyncTaskUpsertWithWhereUniqueWithoutJobInput[]
  createMany?: Prisma.SyncTaskCreateManyJobInputEnvelope
  set?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  disconnect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  delete?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  update?: Prisma.SyncTaskUpdateWithWhereUniqueWithoutJobInput | Prisma.SyncTaskUpdateWithWhereUniqueWithoutJobInput[]
  updateMany?: Prisma.SyncTaskUpdateManyWithWhereWithoutJobInput | Prisma.SyncTaskUpdateManyWithWhereWithoutJobInput[]
  deleteMany?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
}

export type SyncTaskUncheckedUpdateManyWithoutJobNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutJobInput, Prisma.SyncTaskUncheckedCreateWithoutJobInput> | Prisma.SyncTaskCreateWithoutJobInput[] | Prisma.SyncTaskUncheckedCreateWithoutJobInput[]
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutJobInput | Prisma.SyncTaskCreateOrConnectWithoutJobInput[]
  upsert?: Prisma.SyncTaskUpsertWithWhereUniqueWithoutJobInput | Prisma.SyncTaskUpsertWithWhereUniqueWithoutJobInput[]
  createMany?: Prisma.SyncTaskCreateManyJobInputEnvelope
  set?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  disconnect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  delete?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  connect?: Prisma.SyncTaskWhereUniqueInput | Prisma.SyncTaskWhereUniqueInput[]
  update?: Prisma.SyncTaskUpdateWithWhereUniqueWithoutJobInput | Prisma.SyncTaskUpdateWithWhereUniqueWithoutJobInput[]
  updateMany?: Prisma.SyncTaskUpdateManyWithWhereWithoutJobInput | Prisma.SyncTaskUpdateManyWithWhereWithoutJobInput[]
  deleteMany?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
}

export type SyncTaskCreateNestedOneWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutEventsInput, Prisma.SyncTaskUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutEventsInput
  connect?: Prisma.SyncTaskWhereUniqueInput
}

export type SyncTaskUpdateOneRequiredWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.SyncTaskCreateWithoutEventsInput, Prisma.SyncTaskUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.SyncTaskCreateOrConnectWithoutEventsInput
  upsert?: Prisma.SyncTaskUpsertWithoutEventsInput
  connect?: Prisma.SyncTaskWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SyncTaskUpdateToOneWithWhereWithoutEventsInput, Prisma.SyncTaskUpdateWithoutEventsInput>, Prisma.SyncTaskUncheckedUpdateWithoutEventsInput>
}

export type SyncTaskCreateWithoutOrgInput = {
  id?: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSyncTasksInput
  job: Prisma.SyncJobCreateNestedOneWithoutTasksInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutSyncTasksInput
  events?: Prisma.SyncTaskEventCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskUncheckedCreateWithoutOrgInput = {
  id?: string
  userId: string
  jobId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  events?: Prisma.SyncTaskEventUncheckedCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawUncheckedCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskCreateOrConnectWithoutOrgInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutOrgInput, Prisma.SyncTaskUncheckedCreateWithoutOrgInput>
}

export type SyncTaskCreateManyOrgInputEnvelope = {
  data: Prisma.SyncTaskCreateManyOrgInput | Prisma.SyncTaskCreateManyOrgInput[]
  skipDuplicates?: boolean
}

export type SyncTaskUpsertWithWhereUniqueWithoutOrgInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.SyncTaskUpdateWithoutOrgInput, Prisma.SyncTaskUncheckedUpdateWithoutOrgInput>
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutOrgInput, Prisma.SyncTaskUncheckedCreateWithoutOrgInput>
}

export type SyncTaskUpdateWithWhereUniqueWithoutOrgInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateWithoutOrgInput, Prisma.SyncTaskUncheckedUpdateWithoutOrgInput>
}

export type SyncTaskUpdateManyWithWhereWithoutOrgInput = {
  where: Prisma.SyncTaskScalarWhereInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateManyMutationInput, Prisma.SyncTaskUncheckedUpdateManyWithoutOrgInput>
}

export type SyncTaskScalarWhereInput = {
  AND?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
  OR?: Prisma.SyncTaskScalarWhereInput[]
  NOT?: Prisma.SyncTaskScalarWhereInput | Prisma.SyncTaskScalarWhereInput[]
  id?: Prisma.UuidFilter<"SyncTask"> | string
  orgId?: Prisma.UuidFilter<"SyncTask"> | string
  userId?: Prisma.UuidFilter<"SyncTask"> | string
  jobId?: Prisma.UuidFilter<"SyncTask"> | string
  providerAccountId?: Prisma.UuidFilter<"SyncTask"> | string
  spec?: Prisma.JsonFilter<"SyncTask">
  createdAt?: Prisma.DateTimeFilter<"SyncTask"> | Date | string
}

export type SyncTaskCreateWithoutUserInput = {
  id?: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutSyncTasksInput
  job: Prisma.SyncJobCreateNestedOneWithoutTasksInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutSyncTasksInput
  events?: Prisma.SyncTaskEventCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskUncheckedCreateWithoutUserInput = {
  id?: string
  orgId: string
  jobId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  events?: Prisma.SyncTaskEventUncheckedCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawUncheckedCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskCreateOrConnectWithoutUserInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutUserInput, Prisma.SyncTaskUncheckedCreateWithoutUserInput>
}

export type SyncTaskCreateManyUserInputEnvelope = {
  data: Prisma.SyncTaskCreateManyUserInput | Prisma.SyncTaskCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type SyncTaskUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.SyncTaskUpdateWithoutUserInput, Prisma.SyncTaskUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutUserInput, Prisma.SyncTaskUncheckedCreateWithoutUserInput>
}

export type SyncTaskUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateWithoutUserInput, Prisma.SyncTaskUncheckedUpdateWithoutUserInput>
}

export type SyncTaskUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SyncTaskScalarWhereInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateManyMutationInput, Prisma.SyncTaskUncheckedUpdateManyWithoutUserInput>
}

export type SyncTaskCreateWithoutProviderAccountInput = {
  id?: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutSyncTasksInput
  user: Prisma.UserCreateNestedOneWithoutSyncTasksInput
  job: Prisma.SyncJobCreateNestedOneWithoutTasksInput
  events?: Prisma.SyncTaskEventCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskUncheckedCreateWithoutProviderAccountInput = {
  id?: string
  orgId: string
  userId: string
  jobId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  events?: Prisma.SyncTaskEventUncheckedCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawUncheckedCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskCreateOrConnectWithoutProviderAccountInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutProviderAccountInput, Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput>
}

export type SyncTaskCreateManyProviderAccountInputEnvelope = {
  data: Prisma.SyncTaskCreateManyProviderAccountInput | Prisma.SyncTaskCreateManyProviderAccountInput[]
  skipDuplicates?: boolean
}

export type SyncTaskUpsertWithWhereUniqueWithoutProviderAccountInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.SyncTaskUpdateWithoutProviderAccountInput, Prisma.SyncTaskUncheckedUpdateWithoutProviderAccountInput>
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutProviderAccountInput, Prisma.SyncTaskUncheckedCreateWithoutProviderAccountInput>
}

export type SyncTaskUpdateWithWhereUniqueWithoutProviderAccountInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateWithoutProviderAccountInput, Prisma.SyncTaskUncheckedUpdateWithoutProviderAccountInput>
}

export type SyncTaskUpdateManyWithWhereWithoutProviderAccountInput = {
  where: Prisma.SyncTaskScalarWhereInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateManyMutationInput, Prisma.SyncTaskUncheckedUpdateManyWithoutProviderAccountInput>
}

export type SyncTaskCreateWithoutMessageRawsInput = {
  id?: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutSyncTasksInput
  user: Prisma.UserCreateNestedOneWithoutSyncTasksInput
  job: Prisma.SyncJobCreateNestedOneWithoutTasksInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutSyncTasksInput
  events?: Prisma.SyncTaskEventCreateNestedManyWithoutTaskInput
}

export type SyncTaskUncheckedCreateWithoutMessageRawsInput = {
  id?: string
  orgId: string
  userId: string
  jobId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  events?: Prisma.SyncTaskEventUncheckedCreateNestedManyWithoutTaskInput
}

export type SyncTaskCreateOrConnectWithoutMessageRawsInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutMessageRawsInput, Prisma.SyncTaskUncheckedCreateWithoutMessageRawsInput>
}

export type SyncTaskUpsertWithoutMessageRawsInput = {
  update: Prisma.XOR<Prisma.SyncTaskUpdateWithoutMessageRawsInput, Prisma.SyncTaskUncheckedUpdateWithoutMessageRawsInput>
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutMessageRawsInput, Prisma.SyncTaskUncheckedCreateWithoutMessageRawsInput>
  where?: Prisma.SyncTaskWhereInput
}

export type SyncTaskUpdateToOneWithWhereWithoutMessageRawsInput = {
  where?: Prisma.SyncTaskWhereInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateWithoutMessageRawsInput, Prisma.SyncTaskUncheckedUpdateWithoutMessageRawsInput>
}

export type SyncTaskUpdateWithoutMessageRawsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutSyncTasksNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutSyncTasksNestedInput
  job?: Prisma.SyncJobUpdateOneRequiredWithoutTasksNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutSyncTasksNestedInput
  events?: Prisma.SyncTaskEventUpdateManyWithoutTaskNestedInput
}

export type SyncTaskUncheckedUpdateWithoutMessageRawsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.SyncTaskEventUncheckedUpdateManyWithoutTaskNestedInput
}

export type SyncTaskCreateWithoutJobInput = {
  id?: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutSyncTasksInput
  user: Prisma.UserCreateNestedOneWithoutSyncTasksInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutSyncTasksInput
  events?: Prisma.SyncTaskEventCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskUncheckedCreateWithoutJobInput = {
  id?: string
  orgId: string
  userId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  events?: Prisma.SyncTaskEventUncheckedCreateNestedManyWithoutTaskInput
  messageRaws?: Prisma.MessageRawUncheckedCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskCreateOrConnectWithoutJobInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutJobInput, Prisma.SyncTaskUncheckedCreateWithoutJobInput>
}

export type SyncTaskCreateManyJobInputEnvelope = {
  data: Prisma.SyncTaskCreateManyJobInput | Prisma.SyncTaskCreateManyJobInput[]
  skipDuplicates?: boolean
}

export type SyncTaskUpsertWithWhereUniqueWithoutJobInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.SyncTaskUpdateWithoutJobInput, Prisma.SyncTaskUncheckedUpdateWithoutJobInput>
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutJobInput, Prisma.SyncTaskUncheckedCreateWithoutJobInput>
}

export type SyncTaskUpdateWithWhereUniqueWithoutJobInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateWithoutJobInput, Prisma.SyncTaskUncheckedUpdateWithoutJobInput>
}

export type SyncTaskUpdateManyWithWhereWithoutJobInput = {
  where: Prisma.SyncTaskScalarWhereInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateManyMutationInput, Prisma.SyncTaskUncheckedUpdateManyWithoutJobInput>
}

export type SyncTaskCreateWithoutEventsInput = {
  id?: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutSyncTasksInput
  user: Prisma.UserCreateNestedOneWithoutSyncTasksInput
  job: Prisma.SyncJobCreateNestedOneWithoutTasksInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutSyncTasksInput
  messageRaws?: Prisma.MessageRawCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskUncheckedCreateWithoutEventsInput = {
  id?: string
  orgId: string
  userId: string
  jobId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  messageRaws?: Prisma.MessageRawUncheckedCreateNestedManyWithoutSyncTaskInput
}

export type SyncTaskCreateOrConnectWithoutEventsInput = {
  where: Prisma.SyncTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutEventsInput, Prisma.SyncTaskUncheckedCreateWithoutEventsInput>
}

export type SyncTaskUpsertWithoutEventsInput = {
  update: Prisma.XOR<Prisma.SyncTaskUpdateWithoutEventsInput, Prisma.SyncTaskUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.SyncTaskCreateWithoutEventsInput, Prisma.SyncTaskUncheckedCreateWithoutEventsInput>
  where?: Prisma.SyncTaskWhereInput
}

export type SyncTaskUpdateToOneWithWhereWithoutEventsInput = {
  where?: Prisma.SyncTaskWhereInput
  data: Prisma.XOR<Prisma.SyncTaskUpdateWithoutEventsInput, Prisma.SyncTaskUncheckedUpdateWithoutEventsInput>
}

export type SyncTaskUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutSyncTasksNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutSyncTasksNestedInput
  job?: Prisma.SyncJobUpdateOneRequiredWithoutTasksNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutSyncTasksNestedInput
  messageRaws?: Prisma.MessageRawUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messageRaws?: Prisma.MessageRawUncheckedUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskCreateManyOrgInput = {
  id?: string
  userId: string
  jobId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type SyncTaskUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSyncTasksNestedInput
  job?: Prisma.SyncJobUpdateOneRequiredWithoutTasksNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutSyncTasksNestedInput
  events?: Prisma.SyncTaskEventUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.SyncTaskEventUncheckedUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUncheckedUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateManyWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncTaskCreateManyUserInput = {
  id?: string
  orgId: string
  jobId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type SyncTaskUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutSyncTasksNestedInput
  job?: Prisma.SyncJobUpdateOneRequiredWithoutTasksNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutSyncTasksNestedInput
  events?: Prisma.SyncTaskEventUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.SyncTaskEventUncheckedUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUncheckedUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncTaskCreateManyProviderAccountInput = {
  id?: string
  orgId: string
  userId: string
  jobId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type SyncTaskUpdateWithoutProviderAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutSyncTasksNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutSyncTasksNestedInput
  job?: Prisma.SyncJobUpdateOneRequiredWithoutTasksNestedInput
  events?: Prisma.SyncTaskEventUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateWithoutProviderAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.SyncTaskEventUncheckedUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUncheckedUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateManyWithoutProviderAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncTaskCreateManyJobInput = {
  id?: string
  orgId: string
  userId: string
  providerAccountId: string
  spec: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type SyncTaskUpdateWithoutJobInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutSyncTasksNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutSyncTasksNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutSyncTasksNestedInput
  events?: Prisma.SyncTaskEventUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateWithoutJobInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.SyncTaskEventUncheckedUpdateManyWithoutTaskNestedInput
  messageRaws?: Prisma.MessageRawUncheckedUpdateManyWithoutSyncTaskNestedInput
}

export type SyncTaskUncheckedUpdateManyWithoutJobInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  spec?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type SyncTaskCountOutputType
 */

export type SyncTaskCountOutputType = {
  events: number
  messageRaws: number
}

export type SyncTaskCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | SyncTaskCountOutputTypeCountEventsArgs
  messageRaws?: boolean | SyncTaskCountOutputTypeCountMessageRawsArgs
}

/**
 * SyncTaskCountOutputType without action
 */
export type SyncTaskCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTaskCountOutputType
   */
  select?: Prisma.SyncTaskCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SyncTaskCountOutputType without action
 */
export type SyncTaskCountOutputTypeCountEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SyncTaskEventWhereInput
}

/**
 * SyncTaskCountOutputType without action
 */
export type SyncTaskCountOutputTypeCountMessageRawsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageRawWhereInput
}


export type SyncTaskSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orgId?: boolean
  userId?: boolean
  jobId?: boolean
  providerAccountId?: boolean
  spec?: boolean
  createdAt?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  job?: boolean | Prisma.SyncJobDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
  events?: boolean | Prisma.SyncTask$eventsArgs<ExtArgs>
  messageRaws?: boolean | Prisma.SyncTask$messageRawsArgs<ExtArgs>
  _count?: boolean | Prisma.SyncTaskCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["syncTask"]>

export type SyncTaskSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orgId?: boolean
  userId?: boolean
  jobId?: boolean
  providerAccountId?: boolean
  spec?: boolean
  createdAt?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  job?: boolean | Prisma.SyncJobDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["syncTask"]>

export type SyncTaskSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orgId?: boolean
  userId?: boolean
  jobId?: boolean
  providerAccountId?: boolean
  spec?: boolean
  createdAt?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  job?: boolean | Prisma.SyncJobDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["syncTask"]>

export type SyncTaskSelectScalar = {
  id?: boolean
  orgId?: boolean
  userId?: boolean
  jobId?: boolean
  providerAccountId?: boolean
  spec?: boolean
  createdAt?: boolean
}

export type SyncTaskOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orgId" | "userId" | "jobId" | "providerAccountId" | "spec" | "createdAt", ExtArgs["result"]["syncTask"]>
export type SyncTaskInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  job?: boolean | Prisma.SyncJobDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
  events?: boolean | Prisma.SyncTask$eventsArgs<ExtArgs>
  messageRaws?: boolean | Prisma.SyncTask$messageRawsArgs<ExtArgs>
  _count?: boolean | Prisma.SyncTaskCountOutputTypeDefaultArgs<ExtArgs>
}
export type SyncTaskIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  job?: boolean | Prisma.SyncJobDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
}
export type SyncTaskIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  job?: boolean | Prisma.SyncJobDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
}

export type $SyncTaskPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SyncTask"
  objects: {
    org: Prisma.$OrgPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    job: Prisma.$SyncJobPayload<ExtArgs>
    providerAccount: Prisma.$ProviderAccountPayload<ExtArgs>
    events: Prisma.$SyncTaskEventPayload<ExtArgs>[]
    messageRaws: Prisma.$MessageRawPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orgId: string
    userId: string
    jobId: string
    providerAccountId: string
    spec: runtime.JsonValue
    createdAt: Date
  }, ExtArgs["result"]["syncTask"]>
  composites: {}
}

export type SyncTaskGetPayload<S extends boolean | null | undefined | SyncTaskDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload, S>

export type SyncTaskCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SyncTaskFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SyncTaskCountAggregateInputType | true
  }

export interface SyncTaskDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SyncTask'], meta: { name: 'SyncTask' } }
  /**
   * Find zero or one SyncTask that matches the filter.
   * @param {SyncTaskFindUniqueArgs} args - Arguments to find a SyncTask
   * @example
   * // Get one SyncTask
   * const syncTask = await prisma.syncTask.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SyncTaskFindUniqueArgs>(args: Prisma.SelectSubset<T, SyncTaskFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SyncTaskClient<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SyncTask that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SyncTaskFindUniqueOrThrowArgs} args - Arguments to find a SyncTask
   * @example
   * // Get one SyncTask
   * const syncTask = await prisma.syncTask.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SyncTaskFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SyncTaskFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SyncTaskClient<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SyncTask that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncTaskFindFirstArgs} args - Arguments to find a SyncTask
   * @example
   * // Get one SyncTask
   * const syncTask = await prisma.syncTask.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SyncTaskFindFirstArgs>(args?: Prisma.SelectSubset<T, SyncTaskFindFirstArgs<ExtArgs>>): Prisma.Prisma__SyncTaskClient<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SyncTask that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncTaskFindFirstOrThrowArgs} args - Arguments to find a SyncTask
   * @example
   * // Get one SyncTask
   * const syncTask = await prisma.syncTask.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SyncTaskFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SyncTaskFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SyncTaskClient<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SyncTasks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncTaskFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SyncTasks
   * const syncTasks = await prisma.syncTask.findMany()
   * 
   * // Get first 10 SyncTasks
   * const syncTasks = await prisma.syncTask.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const syncTaskWithIdOnly = await prisma.syncTask.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SyncTaskFindManyArgs>(args?: Prisma.SelectSubset<T, SyncTaskFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SyncTask.
   * @param {SyncTaskCreateArgs} args - Arguments to create a SyncTask.
   * @example
   * // Create one SyncTask
   * const SyncTask = await prisma.syncTask.create({
   *   data: {
   *     // ... data to create a SyncTask
   *   }
   * })
   * 
   */
  create<T extends SyncTaskCreateArgs>(args: Prisma.SelectSubset<T, SyncTaskCreateArgs<ExtArgs>>): Prisma.Prisma__SyncTaskClient<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SyncTasks.
   * @param {SyncTaskCreateManyArgs} args - Arguments to create many SyncTasks.
   * @example
   * // Create many SyncTasks
   * const syncTask = await prisma.syncTask.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SyncTaskCreateManyArgs>(args?: Prisma.SelectSubset<T, SyncTaskCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SyncTasks and returns the data saved in the database.
   * @param {SyncTaskCreateManyAndReturnArgs} args - Arguments to create many SyncTasks.
   * @example
   * // Create many SyncTasks
   * const syncTask = await prisma.syncTask.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SyncTasks and only return the `id`
   * const syncTaskWithIdOnly = await prisma.syncTask.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SyncTaskCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SyncTaskCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SyncTask.
   * @param {SyncTaskDeleteArgs} args - Arguments to delete one SyncTask.
   * @example
   * // Delete one SyncTask
   * const SyncTask = await prisma.syncTask.delete({
   *   where: {
   *     // ... filter to delete one SyncTask
   *   }
   * })
   * 
   */
  delete<T extends SyncTaskDeleteArgs>(args: Prisma.SelectSubset<T, SyncTaskDeleteArgs<ExtArgs>>): Prisma.Prisma__SyncTaskClient<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SyncTask.
   * @param {SyncTaskUpdateArgs} args - Arguments to update one SyncTask.
   * @example
   * // Update one SyncTask
   * const syncTask = await prisma.syncTask.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SyncTaskUpdateArgs>(args: Prisma.SelectSubset<T, SyncTaskUpdateArgs<ExtArgs>>): Prisma.Prisma__SyncTaskClient<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SyncTasks.
   * @param {SyncTaskDeleteManyArgs} args - Arguments to filter SyncTasks to delete.
   * @example
   * // Delete a few SyncTasks
   * const { count } = await prisma.syncTask.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SyncTaskDeleteManyArgs>(args?: Prisma.SelectSubset<T, SyncTaskDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SyncTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncTaskUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SyncTasks
   * const syncTask = await prisma.syncTask.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SyncTaskUpdateManyArgs>(args: Prisma.SelectSubset<T, SyncTaskUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SyncTasks and returns the data updated in the database.
   * @param {SyncTaskUpdateManyAndReturnArgs} args - Arguments to update many SyncTasks.
   * @example
   * // Update many SyncTasks
   * const syncTask = await prisma.syncTask.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SyncTasks and only return the `id`
   * const syncTaskWithIdOnly = await prisma.syncTask.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SyncTaskUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SyncTaskUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SyncTask.
   * @param {SyncTaskUpsertArgs} args - Arguments to update or create a SyncTask.
   * @example
   * // Update or create a SyncTask
   * const syncTask = await prisma.syncTask.upsert({
   *   create: {
   *     // ... data to create a SyncTask
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SyncTask we want to update
   *   }
   * })
   */
  upsert<T extends SyncTaskUpsertArgs>(args: Prisma.SelectSubset<T, SyncTaskUpsertArgs<ExtArgs>>): Prisma.Prisma__SyncTaskClient<runtime.Types.Result.GetResult<Prisma.$SyncTaskPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SyncTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncTaskCountArgs} args - Arguments to filter SyncTasks to count.
   * @example
   * // Count the number of SyncTasks
   * const count = await prisma.syncTask.count({
   *   where: {
   *     // ... the filter for the SyncTasks we want to count
   *   }
   * })
  **/
  count<T extends SyncTaskCountArgs>(
    args?: Prisma.Subset<T, SyncTaskCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SyncTaskCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SyncTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncTaskAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SyncTaskAggregateArgs>(args: Prisma.Subset<T, SyncTaskAggregateArgs>): Prisma.PrismaPromise<GetSyncTaskAggregateType<T>>

  /**
   * Group by SyncTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncTaskGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SyncTaskGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SyncTaskGroupByArgs['orderBy'] }
      : { orderBy?: SyncTaskGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SyncTaskGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSyncTaskGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SyncTask model
 */
readonly fields: SyncTaskFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SyncTask.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SyncTaskClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  org<T extends Prisma.OrgDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrgDefaultArgs<ExtArgs>>): Prisma.Prisma__OrgClient<runtime.Types.Result.GetResult<Prisma.$OrgPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  job<T extends Prisma.SyncJobDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SyncJobDefaultArgs<ExtArgs>>): Prisma.Prisma__SyncJobClient<runtime.Types.Result.GetResult<Prisma.$SyncJobPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  providerAccount<T extends Prisma.ProviderAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProviderAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__ProviderAccountClient<runtime.Types.Result.GetResult<Prisma.$ProviderAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  events<T extends Prisma.SyncTask$eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SyncTask$eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncTaskEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  messageRaws<T extends Prisma.SyncTask$messageRawsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SyncTask$messageRawsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageRawPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SyncTask model
 */
export interface SyncTaskFieldRefs {
  readonly id: Prisma.FieldRef<"SyncTask", 'String'>
  readonly orgId: Prisma.FieldRef<"SyncTask", 'String'>
  readonly userId: Prisma.FieldRef<"SyncTask", 'String'>
  readonly jobId: Prisma.FieldRef<"SyncTask", 'String'>
  readonly providerAccountId: Prisma.FieldRef<"SyncTask", 'String'>
  readonly spec: Prisma.FieldRef<"SyncTask", 'Json'>
  readonly createdAt: Prisma.FieldRef<"SyncTask", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SyncTask findUnique
 */
export type SyncTaskFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
  /**
   * Filter, which SyncTask to fetch.
   */
  where: Prisma.SyncTaskWhereUniqueInput
}

/**
 * SyncTask findUniqueOrThrow
 */
export type SyncTaskFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
  /**
   * Filter, which SyncTask to fetch.
   */
  where: Prisma.SyncTaskWhereUniqueInput
}

/**
 * SyncTask findFirst
 */
export type SyncTaskFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
  /**
   * Filter, which SyncTask to fetch.
   */
  where?: Prisma.SyncTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncTasks to fetch.
   */
  orderBy?: Prisma.SyncTaskOrderByWithRelationInput | Prisma.SyncTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SyncTasks.
   */
  cursor?: Prisma.SyncTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncTasks.
   */
  distinct?: Prisma.SyncTaskScalarFieldEnum | Prisma.SyncTaskScalarFieldEnum[]
}

/**
 * SyncTask findFirstOrThrow
 */
export type SyncTaskFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
  /**
   * Filter, which SyncTask to fetch.
   */
  where?: Prisma.SyncTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncTasks to fetch.
   */
  orderBy?: Prisma.SyncTaskOrderByWithRelationInput | Prisma.SyncTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SyncTasks.
   */
  cursor?: Prisma.SyncTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncTasks.
   */
  distinct?: Prisma.SyncTaskScalarFieldEnum | Prisma.SyncTaskScalarFieldEnum[]
}

/**
 * SyncTask findMany
 */
export type SyncTaskFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
  /**
   * Filter, which SyncTasks to fetch.
   */
  where?: Prisma.SyncTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncTasks to fetch.
   */
  orderBy?: Prisma.SyncTaskOrderByWithRelationInput | Prisma.SyncTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SyncTasks.
   */
  cursor?: Prisma.SyncTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncTasks.
   */
  distinct?: Prisma.SyncTaskScalarFieldEnum | Prisma.SyncTaskScalarFieldEnum[]
}

/**
 * SyncTask create
 */
export type SyncTaskCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
  /**
   * The data needed to create a SyncTask.
   */
  data: Prisma.XOR<Prisma.SyncTaskCreateInput, Prisma.SyncTaskUncheckedCreateInput>
}

/**
 * SyncTask createMany
 */
export type SyncTaskCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SyncTasks.
   */
  data: Prisma.SyncTaskCreateManyInput | Prisma.SyncTaskCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SyncTask createManyAndReturn
 */
export type SyncTaskCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * The data used to create many SyncTasks.
   */
  data: Prisma.SyncTaskCreateManyInput | Prisma.SyncTaskCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SyncTask update
 */
export type SyncTaskUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
  /**
   * The data needed to update a SyncTask.
   */
  data: Prisma.XOR<Prisma.SyncTaskUpdateInput, Prisma.SyncTaskUncheckedUpdateInput>
  /**
   * Choose, which SyncTask to update.
   */
  where: Prisma.SyncTaskWhereUniqueInput
}

/**
 * SyncTask updateMany
 */
export type SyncTaskUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SyncTasks.
   */
  data: Prisma.XOR<Prisma.SyncTaskUpdateManyMutationInput, Prisma.SyncTaskUncheckedUpdateManyInput>
  /**
   * Filter which SyncTasks to update
   */
  where?: Prisma.SyncTaskWhereInput
  /**
   * Limit how many SyncTasks to update.
   */
  limit?: number
}

/**
 * SyncTask updateManyAndReturn
 */
export type SyncTaskUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * The data used to update SyncTasks.
   */
  data: Prisma.XOR<Prisma.SyncTaskUpdateManyMutationInput, Prisma.SyncTaskUncheckedUpdateManyInput>
  /**
   * Filter which SyncTasks to update
   */
  where?: Prisma.SyncTaskWhereInput
  /**
   * Limit how many SyncTasks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SyncTask upsert
 */
export type SyncTaskUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
  /**
   * The filter to search for the SyncTask to update in case it exists.
   */
  where: Prisma.SyncTaskWhereUniqueInput
  /**
   * In case the SyncTask found by the `where` argument doesn't exist, create a new SyncTask with this data.
   */
  create: Prisma.XOR<Prisma.SyncTaskCreateInput, Prisma.SyncTaskUncheckedCreateInput>
  /**
   * In case the SyncTask was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SyncTaskUpdateInput, Prisma.SyncTaskUncheckedUpdateInput>
}

/**
 * SyncTask delete
 */
export type SyncTaskDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
  /**
   * Filter which SyncTask to delete.
   */
  where: Prisma.SyncTaskWhereUniqueInput
}

/**
 * SyncTask deleteMany
 */
export type SyncTaskDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SyncTasks to delete
   */
  where?: Prisma.SyncTaskWhereInput
  /**
   * Limit how many SyncTasks to delete.
   */
  limit?: number
}

/**
 * SyncTask.events
 */
export type SyncTask$eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTaskEvent
   */
  select?: Prisma.SyncTaskEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTaskEvent
   */
  omit?: Prisma.SyncTaskEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskEventInclude<ExtArgs> | null
  where?: Prisma.SyncTaskEventWhereInput
  orderBy?: Prisma.SyncTaskEventOrderByWithRelationInput | Prisma.SyncTaskEventOrderByWithRelationInput[]
  cursor?: Prisma.SyncTaskEventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SyncTaskEventScalarFieldEnum | Prisma.SyncTaskEventScalarFieldEnum[]
}

/**
 * SyncTask.messageRaws
 */
export type SyncTask$messageRawsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageRaw
   */
  select?: Prisma.MessageRawSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageRaw
   */
  omit?: Prisma.MessageRawOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageRawInclude<ExtArgs> | null
  where?: Prisma.MessageRawWhereInput
  orderBy?: Prisma.MessageRawOrderByWithRelationInput | Prisma.MessageRawOrderByWithRelationInput[]
  cursor?: Prisma.MessageRawWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MessageRawScalarFieldEnum | Prisma.MessageRawScalarFieldEnum[]
}

/**
 * SyncTask without action
 */
export type SyncTaskDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncTask
   */
  select?: Prisma.SyncTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncTask
   */
  omit?: Prisma.SyncTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncTaskInclude<ExtArgs> | null
}
