
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Thread` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Thread
 * 
 */
export type ThreadModel = runtime.Types.Result.DefaultSelection<Prisma.$ThreadPayload>

export type AggregateThread = {
  _count: ThreadCountAggregateOutputType | null
  _avg: ThreadAvgAggregateOutputType | null
  _sum: ThreadSumAggregateOutputType | null
  _min: ThreadMinAggregateOutputType | null
  _max: ThreadMaxAggregateOutputType | null
}

export type ThreadAvgAggregateOutputType = {
  messageCount: number | null
}

export type ThreadSumAggregateOutputType = {
  messageCount: number | null
}

export type ThreadMinAggregateOutputType = {
  id: string | null
  orgId: string | null
  channel: $Enums.Channel | null
  externalThreadId: string | null
  subject: string | null
  lastMessageAt: Date | null
  messageCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  providerAccountId: string | null
}

export type ThreadMaxAggregateOutputType = {
  id: string | null
  orgId: string | null
  channel: $Enums.Channel | null
  externalThreadId: string | null
  subject: string | null
  lastMessageAt: Date | null
  messageCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  providerAccountId: string | null
}

export type ThreadCountAggregateOutputType = {
  id: number
  orgId: number
  channel: number
  externalThreadId: number
  subject: number
  lastMessageAt: number
  messageCount: number
  createdAt: number
  updatedAt: number
  userId: number
  providerAccountId: number
  _all: number
}


export type ThreadAvgAggregateInputType = {
  messageCount?: true
}

export type ThreadSumAggregateInputType = {
  messageCount?: true
}

export type ThreadMinAggregateInputType = {
  id?: true
  orgId?: true
  channel?: true
  externalThreadId?: true
  subject?: true
  lastMessageAt?: true
  messageCount?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  providerAccountId?: true
}

export type ThreadMaxAggregateInputType = {
  id?: true
  orgId?: true
  channel?: true
  externalThreadId?: true
  subject?: true
  lastMessageAt?: true
  messageCount?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  providerAccountId?: true
}

export type ThreadCountAggregateInputType = {
  id?: true
  orgId?: true
  channel?: true
  externalThreadId?: true
  subject?: true
  lastMessageAt?: true
  messageCount?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  providerAccountId?: true
  _all?: true
}

export type ThreadAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Thread to aggregate.
   */
  where?: Prisma.ThreadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Threads to fetch.
   */
  orderBy?: Prisma.ThreadOrderByWithRelationInput | Prisma.ThreadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ThreadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Threads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Threads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Threads
  **/
  _count?: true | ThreadCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ThreadAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ThreadSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ThreadMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ThreadMaxAggregateInputType
}

export type GetThreadAggregateType<T extends ThreadAggregateArgs> = {
      [P in keyof T & keyof AggregateThread]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateThread[P]>
    : Prisma.GetScalarType<T[P], AggregateThread[P]>
}




export type ThreadGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ThreadWhereInput
  orderBy?: Prisma.ThreadOrderByWithAggregationInput | Prisma.ThreadOrderByWithAggregationInput[]
  by: Prisma.ThreadScalarFieldEnum[] | Prisma.ThreadScalarFieldEnum
  having?: Prisma.ThreadScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ThreadCountAggregateInputType | true
  _avg?: ThreadAvgAggregateInputType
  _sum?: ThreadSumAggregateInputType
  _min?: ThreadMinAggregateInputType
  _max?: ThreadMaxAggregateInputType
}

export type ThreadGroupByOutputType = {
  id: string
  orgId: string
  channel: $Enums.Channel
  externalThreadId: string | null
  subject: string | null
  lastMessageAt: Date | null
  messageCount: number
  createdAt: Date
  updatedAt: Date
  userId: string
  providerAccountId: string
  _count: ThreadCountAggregateOutputType | null
  _avg: ThreadAvgAggregateOutputType | null
  _sum: ThreadSumAggregateOutputType | null
  _min: ThreadMinAggregateOutputType | null
  _max: ThreadMaxAggregateOutputType | null
}

export type GetThreadGroupByPayload<T extends ThreadGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ThreadGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ThreadGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ThreadGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ThreadGroupByOutputType[P]>
      }
    >
  >



export type ThreadWhereInput = {
  AND?: Prisma.ThreadWhereInput | Prisma.ThreadWhereInput[]
  OR?: Prisma.ThreadWhereInput[]
  NOT?: Prisma.ThreadWhereInput | Prisma.ThreadWhereInput[]
  id?: Prisma.UuidFilter<"Thread"> | string
  orgId?: Prisma.UuidFilter<"Thread"> | string
  channel?: Prisma.EnumChannelFilter<"Thread"> | $Enums.Channel
  externalThreadId?: Prisma.StringNullableFilter<"Thread"> | string | null
  subject?: Prisma.StringNullableFilter<"Thread"> | string | null
  lastMessageAt?: Prisma.DateTimeNullableFilter<"Thread"> | Date | string | null
  messageCount?: Prisma.IntFilter<"Thread"> | number
  createdAt?: Prisma.DateTimeFilter<"Thread"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Thread"> | Date | string
  userId?: Prisma.UuidFilter<"Thread"> | string
  providerAccountId?: Prisma.UuidFilter<"Thread"> | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  providerAccount?: Prisma.XOR<Prisma.ProviderAccountScalarRelationFilter, Prisma.ProviderAccountWhereInput>
  messages?: Prisma.MessageListRelationFilter
}

export type ThreadOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  externalThreadId?: Prisma.SortOrderInput | Prisma.SortOrder
  subject?: Prisma.SortOrderInput | Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrderInput | Prisma.SortOrder
  messageCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
  org?: Prisma.OrgOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  providerAccount?: Prisma.ProviderAccountOrderByWithRelationInput
  messages?: Prisma.MessageOrderByRelationAggregateInput
}

export type ThreadWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  providerAccountId_externalThreadId?: Prisma.ThreadProviderAccountIdExternalThreadIdCompoundUniqueInput
  AND?: Prisma.ThreadWhereInput | Prisma.ThreadWhereInput[]
  OR?: Prisma.ThreadWhereInput[]
  NOT?: Prisma.ThreadWhereInput | Prisma.ThreadWhereInput[]
  orgId?: Prisma.UuidFilter<"Thread"> | string
  channel?: Prisma.EnumChannelFilter<"Thread"> | $Enums.Channel
  externalThreadId?: Prisma.StringNullableFilter<"Thread"> | string | null
  subject?: Prisma.StringNullableFilter<"Thread"> | string | null
  lastMessageAt?: Prisma.DateTimeNullableFilter<"Thread"> | Date | string | null
  messageCount?: Prisma.IntFilter<"Thread"> | number
  createdAt?: Prisma.DateTimeFilter<"Thread"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Thread"> | Date | string
  userId?: Prisma.UuidFilter<"Thread"> | string
  providerAccountId?: Prisma.UuidFilter<"Thread"> | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  providerAccount?: Prisma.XOR<Prisma.ProviderAccountScalarRelationFilter, Prisma.ProviderAccountWhereInput>
  messages?: Prisma.MessageListRelationFilter
}, "id" | "providerAccountId_externalThreadId">

export type ThreadOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  externalThreadId?: Prisma.SortOrderInput | Prisma.SortOrder
  subject?: Prisma.SortOrderInput | Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrderInput | Prisma.SortOrder
  messageCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
  _count?: Prisma.ThreadCountOrderByAggregateInput
  _avg?: Prisma.ThreadAvgOrderByAggregateInput
  _max?: Prisma.ThreadMaxOrderByAggregateInput
  _min?: Prisma.ThreadMinOrderByAggregateInput
  _sum?: Prisma.ThreadSumOrderByAggregateInput
}

export type ThreadScalarWhereWithAggregatesInput = {
  AND?: Prisma.ThreadScalarWhereWithAggregatesInput | Prisma.ThreadScalarWhereWithAggregatesInput[]
  OR?: Prisma.ThreadScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ThreadScalarWhereWithAggregatesInput | Prisma.ThreadScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Thread"> | string
  orgId?: Prisma.UuidWithAggregatesFilter<"Thread"> | string
  channel?: Prisma.EnumChannelWithAggregatesFilter<"Thread"> | $Enums.Channel
  externalThreadId?: Prisma.StringNullableWithAggregatesFilter<"Thread"> | string | null
  subject?: Prisma.StringNullableWithAggregatesFilter<"Thread"> | string | null
  lastMessageAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Thread"> | Date | string | null
  messageCount?: Prisma.IntWithAggregatesFilter<"Thread"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Thread"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Thread"> | Date | string
  userId?: Prisma.UuidWithAggregatesFilter<"Thread"> | string
  providerAccountId?: Prisma.UuidWithAggregatesFilter<"Thread"> | string
}

export type ThreadCreateInput = {
  id?: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutThreadsInput
  user: Prisma.UserCreateNestedOneWithoutThreadsInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutThreadsInput
  messages?: Prisma.MessageCreateNestedManyWithoutThreadInput
}

export type ThreadUncheckedCreateInput = {
  id?: string
  orgId: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  providerAccountId: string
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutThreadInput
}

export type ThreadUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutThreadsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutThreadsNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutThreadsNestedInput
  messages?: Prisma.MessageUpdateManyWithoutThreadNestedInput
}

export type ThreadUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  messages?: Prisma.MessageUncheckedUpdateManyWithoutThreadNestedInput
}

export type ThreadCreateManyInput = {
  id?: string
  orgId: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  providerAccountId: string
}

export type ThreadUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ThreadUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ThreadListRelationFilter = {
  every?: Prisma.ThreadWhereInput
  some?: Prisma.ThreadWhereInput
  none?: Prisma.ThreadWhereInput
}

export type ThreadOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ThreadProviderAccountIdExternalThreadIdCompoundUniqueInput = {
  providerAccountId: string
  externalThreadId: string
}

export type ThreadCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  externalThreadId?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrder
  messageCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
}

export type ThreadAvgOrderByAggregateInput = {
  messageCount?: Prisma.SortOrder
}

export type ThreadMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  externalThreadId?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrder
  messageCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
}

export type ThreadMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  externalThreadId?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrder
  messageCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  providerAccountId?: Prisma.SortOrder
}

export type ThreadSumOrderByAggregateInput = {
  messageCount?: Prisma.SortOrder
}

export type ThreadNullableScalarRelationFilter = {
  is?: Prisma.ThreadWhereInput | null
  isNot?: Prisma.ThreadWhereInput | null
}

export type ThreadCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutOrgInput, Prisma.ThreadUncheckedCreateWithoutOrgInput> | Prisma.ThreadCreateWithoutOrgInput[] | Prisma.ThreadUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutOrgInput | Prisma.ThreadCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.ThreadCreateManyOrgInputEnvelope
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
}

export type ThreadUncheckedCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutOrgInput, Prisma.ThreadUncheckedCreateWithoutOrgInput> | Prisma.ThreadCreateWithoutOrgInput[] | Prisma.ThreadUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutOrgInput | Prisma.ThreadCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.ThreadCreateManyOrgInputEnvelope
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
}

export type ThreadUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutOrgInput, Prisma.ThreadUncheckedCreateWithoutOrgInput> | Prisma.ThreadCreateWithoutOrgInput[] | Prisma.ThreadUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutOrgInput | Prisma.ThreadCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.ThreadUpsertWithWhereUniqueWithoutOrgInput | Prisma.ThreadUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.ThreadCreateManyOrgInputEnvelope
  set?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  disconnect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  delete?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  update?: Prisma.ThreadUpdateWithWhereUniqueWithoutOrgInput | Prisma.ThreadUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.ThreadUpdateManyWithWhereWithoutOrgInput | Prisma.ThreadUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.ThreadScalarWhereInput | Prisma.ThreadScalarWhereInput[]
}

export type ThreadUncheckedUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutOrgInput, Prisma.ThreadUncheckedCreateWithoutOrgInput> | Prisma.ThreadCreateWithoutOrgInput[] | Prisma.ThreadUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutOrgInput | Prisma.ThreadCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.ThreadUpsertWithWhereUniqueWithoutOrgInput | Prisma.ThreadUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.ThreadCreateManyOrgInputEnvelope
  set?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  disconnect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  delete?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  update?: Prisma.ThreadUpdateWithWhereUniqueWithoutOrgInput | Prisma.ThreadUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.ThreadUpdateManyWithWhereWithoutOrgInput | Prisma.ThreadUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.ThreadScalarWhereInput | Prisma.ThreadScalarWhereInput[]
}

export type ThreadCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutUserInput, Prisma.ThreadUncheckedCreateWithoutUserInput> | Prisma.ThreadCreateWithoutUserInput[] | Prisma.ThreadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutUserInput | Prisma.ThreadCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ThreadCreateManyUserInputEnvelope
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
}

export type ThreadUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutUserInput, Prisma.ThreadUncheckedCreateWithoutUserInput> | Prisma.ThreadCreateWithoutUserInput[] | Prisma.ThreadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutUserInput | Prisma.ThreadCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ThreadCreateManyUserInputEnvelope
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
}

export type ThreadUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutUserInput, Prisma.ThreadUncheckedCreateWithoutUserInput> | Prisma.ThreadCreateWithoutUserInput[] | Prisma.ThreadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutUserInput | Prisma.ThreadCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ThreadUpsertWithWhereUniqueWithoutUserInput | Prisma.ThreadUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ThreadCreateManyUserInputEnvelope
  set?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  disconnect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  delete?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  update?: Prisma.ThreadUpdateWithWhereUniqueWithoutUserInput | Prisma.ThreadUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ThreadUpdateManyWithWhereWithoutUserInput | Prisma.ThreadUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ThreadScalarWhereInput | Prisma.ThreadScalarWhereInput[]
}

export type ThreadUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutUserInput, Prisma.ThreadUncheckedCreateWithoutUserInput> | Prisma.ThreadCreateWithoutUserInput[] | Prisma.ThreadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutUserInput | Prisma.ThreadCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ThreadUpsertWithWhereUniqueWithoutUserInput | Prisma.ThreadUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ThreadCreateManyUserInputEnvelope
  set?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  disconnect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  delete?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  update?: Prisma.ThreadUpdateWithWhereUniqueWithoutUserInput | Prisma.ThreadUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ThreadUpdateManyWithWhereWithoutUserInput | Prisma.ThreadUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ThreadScalarWhereInput | Prisma.ThreadScalarWhereInput[]
}

export type ThreadCreateNestedManyWithoutProviderAccountInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutProviderAccountInput, Prisma.ThreadUncheckedCreateWithoutProviderAccountInput> | Prisma.ThreadCreateWithoutProviderAccountInput[] | Prisma.ThreadUncheckedCreateWithoutProviderAccountInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutProviderAccountInput | Prisma.ThreadCreateOrConnectWithoutProviderAccountInput[]
  createMany?: Prisma.ThreadCreateManyProviderAccountInputEnvelope
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
}

export type ThreadUncheckedCreateNestedManyWithoutProviderAccountInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutProviderAccountInput, Prisma.ThreadUncheckedCreateWithoutProviderAccountInput> | Prisma.ThreadCreateWithoutProviderAccountInput[] | Prisma.ThreadUncheckedCreateWithoutProviderAccountInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutProviderAccountInput | Prisma.ThreadCreateOrConnectWithoutProviderAccountInput[]
  createMany?: Prisma.ThreadCreateManyProviderAccountInputEnvelope
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
}

export type ThreadUpdateManyWithoutProviderAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutProviderAccountInput, Prisma.ThreadUncheckedCreateWithoutProviderAccountInput> | Prisma.ThreadCreateWithoutProviderAccountInput[] | Prisma.ThreadUncheckedCreateWithoutProviderAccountInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutProviderAccountInput | Prisma.ThreadCreateOrConnectWithoutProviderAccountInput[]
  upsert?: Prisma.ThreadUpsertWithWhereUniqueWithoutProviderAccountInput | Prisma.ThreadUpsertWithWhereUniqueWithoutProviderAccountInput[]
  createMany?: Prisma.ThreadCreateManyProviderAccountInputEnvelope
  set?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  disconnect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  delete?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  update?: Prisma.ThreadUpdateWithWhereUniqueWithoutProviderAccountInput | Prisma.ThreadUpdateWithWhereUniqueWithoutProviderAccountInput[]
  updateMany?: Prisma.ThreadUpdateManyWithWhereWithoutProviderAccountInput | Prisma.ThreadUpdateManyWithWhereWithoutProviderAccountInput[]
  deleteMany?: Prisma.ThreadScalarWhereInput | Prisma.ThreadScalarWhereInput[]
}

export type ThreadUncheckedUpdateManyWithoutProviderAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutProviderAccountInput, Prisma.ThreadUncheckedCreateWithoutProviderAccountInput> | Prisma.ThreadCreateWithoutProviderAccountInput[] | Prisma.ThreadUncheckedCreateWithoutProviderAccountInput[]
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutProviderAccountInput | Prisma.ThreadCreateOrConnectWithoutProviderAccountInput[]
  upsert?: Prisma.ThreadUpsertWithWhereUniqueWithoutProviderAccountInput | Prisma.ThreadUpsertWithWhereUniqueWithoutProviderAccountInput[]
  createMany?: Prisma.ThreadCreateManyProviderAccountInputEnvelope
  set?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  disconnect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  delete?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  connect?: Prisma.ThreadWhereUniqueInput | Prisma.ThreadWhereUniqueInput[]
  update?: Prisma.ThreadUpdateWithWhereUniqueWithoutProviderAccountInput | Prisma.ThreadUpdateWithWhereUniqueWithoutProviderAccountInput[]
  updateMany?: Prisma.ThreadUpdateManyWithWhereWithoutProviderAccountInput | Prisma.ThreadUpdateManyWithWhereWithoutProviderAccountInput[]
  deleteMany?: Prisma.ThreadScalarWhereInput | Prisma.ThreadScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ThreadCreateNestedOneWithoutMessagesInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutMessagesInput, Prisma.ThreadUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutMessagesInput
  connect?: Prisma.ThreadWhereUniqueInput
}

export type ThreadUpdateOneWithoutMessagesNestedInput = {
  create?: Prisma.XOR<Prisma.ThreadCreateWithoutMessagesInput, Prisma.ThreadUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.ThreadCreateOrConnectWithoutMessagesInput
  upsert?: Prisma.ThreadUpsertWithoutMessagesInput
  disconnect?: Prisma.ThreadWhereInput | boolean
  delete?: Prisma.ThreadWhereInput | boolean
  connect?: Prisma.ThreadWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ThreadUpdateToOneWithWhereWithoutMessagesInput, Prisma.ThreadUpdateWithoutMessagesInput>, Prisma.ThreadUncheckedUpdateWithoutMessagesInput>
}

export type ThreadCreateWithoutOrgInput = {
  id?: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutThreadsInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutThreadsInput
  messages?: Prisma.MessageCreateNestedManyWithoutThreadInput
}

export type ThreadUncheckedCreateWithoutOrgInput = {
  id?: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  providerAccountId: string
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutThreadInput
}

export type ThreadCreateOrConnectWithoutOrgInput = {
  where: Prisma.ThreadWhereUniqueInput
  create: Prisma.XOR<Prisma.ThreadCreateWithoutOrgInput, Prisma.ThreadUncheckedCreateWithoutOrgInput>
}

export type ThreadCreateManyOrgInputEnvelope = {
  data: Prisma.ThreadCreateManyOrgInput | Prisma.ThreadCreateManyOrgInput[]
  skipDuplicates?: boolean
}

export type ThreadUpsertWithWhereUniqueWithoutOrgInput = {
  where: Prisma.ThreadWhereUniqueInput
  update: Prisma.XOR<Prisma.ThreadUpdateWithoutOrgInput, Prisma.ThreadUncheckedUpdateWithoutOrgInput>
  create: Prisma.XOR<Prisma.ThreadCreateWithoutOrgInput, Prisma.ThreadUncheckedCreateWithoutOrgInput>
}

export type ThreadUpdateWithWhereUniqueWithoutOrgInput = {
  where: Prisma.ThreadWhereUniqueInput
  data: Prisma.XOR<Prisma.ThreadUpdateWithoutOrgInput, Prisma.ThreadUncheckedUpdateWithoutOrgInput>
}

export type ThreadUpdateManyWithWhereWithoutOrgInput = {
  where: Prisma.ThreadScalarWhereInput
  data: Prisma.XOR<Prisma.ThreadUpdateManyMutationInput, Prisma.ThreadUncheckedUpdateManyWithoutOrgInput>
}

export type ThreadScalarWhereInput = {
  AND?: Prisma.ThreadScalarWhereInput | Prisma.ThreadScalarWhereInput[]
  OR?: Prisma.ThreadScalarWhereInput[]
  NOT?: Prisma.ThreadScalarWhereInput | Prisma.ThreadScalarWhereInput[]
  id?: Prisma.UuidFilter<"Thread"> | string
  orgId?: Prisma.UuidFilter<"Thread"> | string
  channel?: Prisma.EnumChannelFilter<"Thread"> | $Enums.Channel
  externalThreadId?: Prisma.StringNullableFilter<"Thread"> | string | null
  subject?: Prisma.StringNullableFilter<"Thread"> | string | null
  lastMessageAt?: Prisma.DateTimeNullableFilter<"Thread"> | Date | string | null
  messageCount?: Prisma.IntFilter<"Thread"> | number
  createdAt?: Prisma.DateTimeFilter<"Thread"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Thread"> | Date | string
  userId?: Prisma.UuidFilter<"Thread"> | string
  providerAccountId?: Prisma.UuidFilter<"Thread"> | string
}

export type ThreadCreateWithoutUserInput = {
  id?: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutThreadsInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutThreadsInput
  messages?: Prisma.MessageCreateNestedManyWithoutThreadInput
}

export type ThreadUncheckedCreateWithoutUserInput = {
  id?: string
  orgId: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  providerAccountId: string
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutThreadInput
}

export type ThreadCreateOrConnectWithoutUserInput = {
  where: Prisma.ThreadWhereUniqueInput
  create: Prisma.XOR<Prisma.ThreadCreateWithoutUserInput, Prisma.ThreadUncheckedCreateWithoutUserInput>
}

export type ThreadCreateManyUserInputEnvelope = {
  data: Prisma.ThreadCreateManyUserInput | Prisma.ThreadCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ThreadUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ThreadWhereUniqueInput
  update: Prisma.XOR<Prisma.ThreadUpdateWithoutUserInput, Prisma.ThreadUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ThreadCreateWithoutUserInput, Prisma.ThreadUncheckedCreateWithoutUserInput>
}

export type ThreadUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ThreadWhereUniqueInput
  data: Prisma.XOR<Prisma.ThreadUpdateWithoutUserInput, Prisma.ThreadUncheckedUpdateWithoutUserInput>
}

export type ThreadUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ThreadScalarWhereInput
  data: Prisma.XOR<Prisma.ThreadUpdateManyMutationInput, Prisma.ThreadUncheckedUpdateManyWithoutUserInput>
}

export type ThreadCreateWithoutProviderAccountInput = {
  id?: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutThreadsInput
  user: Prisma.UserCreateNestedOneWithoutThreadsInput
  messages?: Prisma.MessageCreateNestedManyWithoutThreadInput
}

export type ThreadUncheckedCreateWithoutProviderAccountInput = {
  id?: string
  orgId: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutThreadInput
}

export type ThreadCreateOrConnectWithoutProviderAccountInput = {
  where: Prisma.ThreadWhereUniqueInput
  create: Prisma.XOR<Prisma.ThreadCreateWithoutProviderAccountInput, Prisma.ThreadUncheckedCreateWithoutProviderAccountInput>
}

export type ThreadCreateManyProviderAccountInputEnvelope = {
  data: Prisma.ThreadCreateManyProviderAccountInput | Prisma.ThreadCreateManyProviderAccountInput[]
  skipDuplicates?: boolean
}

export type ThreadUpsertWithWhereUniqueWithoutProviderAccountInput = {
  where: Prisma.ThreadWhereUniqueInput
  update: Prisma.XOR<Prisma.ThreadUpdateWithoutProviderAccountInput, Prisma.ThreadUncheckedUpdateWithoutProviderAccountInput>
  create: Prisma.XOR<Prisma.ThreadCreateWithoutProviderAccountInput, Prisma.ThreadUncheckedCreateWithoutProviderAccountInput>
}

export type ThreadUpdateWithWhereUniqueWithoutProviderAccountInput = {
  where: Prisma.ThreadWhereUniqueInput
  data: Prisma.XOR<Prisma.ThreadUpdateWithoutProviderAccountInput, Prisma.ThreadUncheckedUpdateWithoutProviderAccountInput>
}

export type ThreadUpdateManyWithWhereWithoutProviderAccountInput = {
  where: Prisma.ThreadScalarWhereInput
  data: Prisma.XOR<Prisma.ThreadUpdateManyMutationInput, Prisma.ThreadUncheckedUpdateManyWithoutProviderAccountInput>
}

export type ThreadCreateWithoutMessagesInput = {
  id?: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutThreadsInput
  user: Prisma.UserCreateNestedOneWithoutThreadsInput
  providerAccount: Prisma.ProviderAccountCreateNestedOneWithoutThreadsInput
}

export type ThreadUncheckedCreateWithoutMessagesInput = {
  id?: string
  orgId: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  providerAccountId: string
}

export type ThreadCreateOrConnectWithoutMessagesInput = {
  where: Prisma.ThreadWhereUniqueInput
  create: Prisma.XOR<Prisma.ThreadCreateWithoutMessagesInput, Prisma.ThreadUncheckedCreateWithoutMessagesInput>
}

export type ThreadUpsertWithoutMessagesInput = {
  update: Prisma.XOR<Prisma.ThreadUpdateWithoutMessagesInput, Prisma.ThreadUncheckedUpdateWithoutMessagesInput>
  create: Prisma.XOR<Prisma.ThreadCreateWithoutMessagesInput, Prisma.ThreadUncheckedCreateWithoutMessagesInput>
  where?: Prisma.ThreadWhereInput
}

export type ThreadUpdateToOneWithWhereWithoutMessagesInput = {
  where?: Prisma.ThreadWhereInput
  data: Prisma.XOR<Prisma.ThreadUpdateWithoutMessagesInput, Prisma.ThreadUncheckedUpdateWithoutMessagesInput>
}

export type ThreadUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutThreadsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutThreadsNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutThreadsNestedInput
}

export type ThreadUncheckedUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ThreadCreateManyOrgInput = {
  id?: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  providerAccountId: string
}

export type ThreadUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutThreadsNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutThreadsNestedInput
  messages?: Prisma.MessageUpdateManyWithoutThreadNestedInput
}

export type ThreadUncheckedUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  messages?: Prisma.MessageUncheckedUpdateManyWithoutThreadNestedInput
}

export type ThreadUncheckedUpdateManyWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ThreadCreateManyUserInput = {
  id?: string
  orgId: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  providerAccountId: string
}

export type ThreadUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutThreadsNestedInput
  providerAccount?: Prisma.ProviderAccountUpdateOneRequiredWithoutThreadsNestedInput
  messages?: Prisma.MessageUpdateManyWithoutThreadNestedInput
}

export type ThreadUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  messages?: Prisma.MessageUncheckedUpdateManyWithoutThreadNestedInput
}

export type ThreadUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  providerAccountId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ThreadCreateManyProviderAccountInput = {
  id?: string
  orgId: string
  channel: $Enums.Channel
  externalThreadId?: string | null
  subject?: string | null
  lastMessageAt?: Date | string | null
  messageCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
}

export type ThreadUpdateWithoutProviderAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutThreadsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutThreadsNestedInput
  messages?: Prisma.MessageUpdateManyWithoutThreadNestedInput
}

export type ThreadUncheckedUpdateWithoutProviderAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messages?: Prisma.MessageUncheckedUpdateManyWithoutThreadNestedInput
}

export type ThreadUncheckedUpdateManyWithoutProviderAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  externalThreadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messageCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ThreadCountOutputType
 */

export type ThreadCountOutputType = {
  messages: number
}

export type ThreadCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  messages?: boolean | ThreadCountOutputTypeCountMessagesArgs
}

/**
 * ThreadCountOutputType without action
 */
export type ThreadCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadCountOutputType
   */
  select?: Prisma.ThreadCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ThreadCountOutputType without action
 */
export type ThreadCountOutputTypeCountMessagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageWhereInput
}


export type ThreadSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orgId?: boolean
  channel?: boolean
  externalThreadId?: boolean
  subject?: boolean
  lastMessageAt?: boolean
  messageCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  providerAccountId?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
  messages?: boolean | Prisma.Thread$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.ThreadCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["thread"]>

export type ThreadSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orgId?: boolean
  channel?: boolean
  externalThreadId?: boolean
  subject?: boolean
  lastMessageAt?: boolean
  messageCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  providerAccountId?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["thread"]>

export type ThreadSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orgId?: boolean
  channel?: boolean
  externalThreadId?: boolean
  subject?: boolean
  lastMessageAt?: boolean
  messageCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  providerAccountId?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["thread"]>

export type ThreadSelectScalar = {
  id?: boolean
  orgId?: boolean
  channel?: boolean
  externalThreadId?: boolean
  subject?: boolean
  lastMessageAt?: boolean
  messageCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  providerAccountId?: boolean
}

export type ThreadOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orgId" | "channel" | "externalThreadId" | "subject" | "lastMessageAt" | "messageCount" | "createdAt" | "updatedAt" | "userId" | "providerAccountId", ExtArgs["result"]["thread"]>
export type ThreadInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
  messages?: boolean | Prisma.Thread$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.ThreadCountOutputTypeDefaultArgs<ExtArgs>
}
export type ThreadIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
}
export type ThreadIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  providerAccount?: boolean | Prisma.ProviderAccountDefaultArgs<ExtArgs>
}

export type $ThreadPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Thread"
  objects: {
    org: Prisma.$OrgPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    providerAccount: Prisma.$ProviderAccountPayload<ExtArgs>
    messages: Prisma.$MessagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orgId: string
    channel: $Enums.Channel
    externalThreadId: string | null
    subject: string | null
    lastMessageAt: Date | null
    messageCount: number
    createdAt: Date
    updatedAt: Date
    userId: string
    providerAccountId: string
  }, ExtArgs["result"]["thread"]>
  composites: {}
}

export type ThreadGetPayload<S extends boolean | null | undefined | ThreadDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ThreadPayload, S>

export type ThreadCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ThreadFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ThreadCountAggregateInputType | true
  }

export interface ThreadDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Thread'], meta: { name: 'Thread' } }
  /**
   * Find zero or one Thread that matches the filter.
   * @param {ThreadFindUniqueArgs} args - Arguments to find a Thread
   * @example
   * // Get one Thread
   * const thread = await prisma.thread.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ThreadFindUniqueArgs>(args: Prisma.SelectSubset<T, ThreadFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ThreadClient<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Thread that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ThreadFindUniqueOrThrowArgs} args - Arguments to find a Thread
   * @example
   * // Get one Thread
   * const thread = await prisma.thread.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ThreadFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ThreadFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ThreadClient<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Thread that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadFindFirstArgs} args - Arguments to find a Thread
   * @example
   * // Get one Thread
   * const thread = await prisma.thread.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ThreadFindFirstArgs>(args?: Prisma.SelectSubset<T, ThreadFindFirstArgs<ExtArgs>>): Prisma.Prisma__ThreadClient<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Thread that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadFindFirstOrThrowArgs} args - Arguments to find a Thread
   * @example
   * // Get one Thread
   * const thread = await prisma.thread.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ThreadFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ThreadFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ThreadClient<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Threads that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Threads
   * const threads = await prisma.thread.findMany()
   * 
   * // Get first 10 Threads
   * const threads = await prisma.thread.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const threadWithIdOnly = await prisma.thread.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ThreadFindManyArgs>(args?: Prisma.SelectSubset<T, ThreadFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Thread.
   * @param {ThreadCreateArgs} args - Arguments to create a Thread.
   * @example
   * // Create one Thread
   * const Thread = await prisma.thread.create({
   *   data: {
   *     // ... data to create a Thread
   *   }
   * })
   * 
   */
  create<T extends ThreadCreateArgs>(args: Prisma.SelectSubset<T, ThreadCreateArgs<ExtArgs>>): Prisma.Prisma__ThreadClient<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Threads.
   * @param {ThreadCreateManyArgs} args - Arguments to create many Threads.
   * @example
   * // Create many Threads
   * const thread = await prisma.thread.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ThreadCreateManyArgs>(args?: Prisma.SelectSubset<T, ThreadCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Threads and returns the data saved in the database.
   * @param {ThreadCreateManyAndReturnArgs} args - Arguments to create many Threads.
   * @example
   * // Create many Threads
   * const thread = await prisma.thread.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Threads and only return the `id`
   * const threadWithIdOnly = await prisma.thread.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ThreadCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ThreadCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Thread.
   * @param {ThreadDeleteArgs} args - Arguments to delete one Thread.
   * @example
   * // Delete one Thread
   * const Thread = await prisma.thread.delete({
   *   where: {
   *     // ... filter to delete one Thread
   *   }
   * })
   * 
   */
  delete<T extends ThreadDeleteArgs>(args: Prisma.SelectSubset<T, ThreadDeleteArgs<ExtArgs>>): Prisma.Prisma__ThreadClient<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Thread.
   * @param {ThreadUpdateArgs} args - Arguments to update one Thread.
   * @example
   * // Update one Thread
   * const thread = await prisma.thread.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ThreadUpdateArgs>(args: Prisma.SelectSubset<T, ThreadUpdateArgs<ExtArgs>>): Prisma.Prisma__ThreadClient<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Threads.
   * @param {ThreadDeleteManyArgs} args - Arguments to filter Threads to delete.
   * @example
   * // Delete a few Threads
   * const { count } = await prisma.thread.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ThreadDeleteManyArgs>(args?: Prisma.SelectSubset<T, ThreadDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Threads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Threads
   * const thread = await prisma.thread.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ThreadUpdateManyArgs>(args: Prisma.SelectSubset<T, ThreadUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Threads and returns the data updated in the database.
   * @param {ThreadUpdateManyAndReturnArgs} args - Arguments to update many Threads.
   * @example
   * // Update many Threads
   * const thread = await prisma.thread.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Threads and only return the `id`
   * const threadWithIdOnly = await prisma.thread.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ThreadUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ThreadUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Thread.
   * @param {ThreadUpsertArgs} args - Arguments to update or create a Thread.
   * @example
   * // Update or create a Thread
   * const thread = await prisma.thread.upsert({
   *   create: {
   *     // ... data to create a Thread
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Thread we want to update
   *   }
   * })
   */
  upsert<T extends ThreadUpsertArgs>(args: Prisma.SelectSubset<T, ThreadUpsertArgs<ExtArgs>>): Prisma.Prisma__ThreadClient<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Threads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadCountArgs} args - Arguments to filter Threads to count.
   * @example
   * // Count the number of Threads
   * const count = await prisma.thread.count({
   *   where: {
   *     // ... the filter for the Threads we want to count
   *   }
   * })
  **/
  count<T extends ThreadCountArgs>(
    args?: Prisma.Subset<T, ThreadCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ThreadCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Thread.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ThreadAggregateArgs>(args: Prisma.Subset<T, ThreadAggregateArgs>): Prisma.PrismaPromise<GetThreadAggregateType<T>>

  /**
   * Group by Thread.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ThreadGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ThreadGroupByArgs['orderBy'] }
      : { orderBy?: ThreadGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ThreadGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetThreadGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Thread model
 */
readonly fields: ThreadFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Thread.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ThreadClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  org<T extends Prisma.OrgDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrgDefaultArgs<ExtArgs>>): Prisma.Prisma__OrgClient<runtime.Types.Result.GetResult<Prisma.$OrgPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  providerAccount<T extends Prisma.ProviderAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProviderAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__ProviderAccountClient<runtime.Types.Result.GetResult<Prisma.$ProviderAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  messages<T extends Prisma.Thread$messagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Thread$messagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Thread model
 */
export interface ThreadFieldRefs {
  readonly id: Prisma.FieldRef<"Thread", 'String'>
  readonly orgId: Prisma.FieldRef<"Thread", 'String'>
  readonly channel: Prisma.FieldRef<"Thread", 'Channel'>
  readonly externalThreadId: Prisma.FieldRef<"Thread", 'String'>
  readonly subject: Prisma.FieldRef<"Thread", 'String'>
  readonly lastMessageAt: Prisma.FieldRef<"Thread", 'DateTime'>
  readonly messageCount: Prisma.FieldRef<"Thread", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Thread", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Thread", 'DateTime'>
  readonly userId: Prisma.FieldRef<"Thread", 'String'>
  readonly providerAccountId: Prisma.FieldRef<"Thread", 'String'>
}
    

// Custom InputTypes
/**
 * Thread findUnique
 */
export type ThreadFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
  /**
   * Filter, which Thread to fetch.
   */
  where: Prisma.ThreadWhereUniqueInput
}

/**
 * Thread findUniqueOrThrow
 */
export type ThreadFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
  /**
   * Filter, which Thread to fetch.
   */
  where: Prisma.ThreadWhereUniqueInput
}

/**
 * Thread findFirst
 */
export type ThreadFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
  /**
   * Filter, which Thread to fetch.
   */
  where?: Prisma.ThreadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Threads to fetch.
   */
  orderBy?: Prisma.ThreadOrderByWithRelationInput | Prisma.ThreadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Threads.
   */
  cursor?: Prisma.ThreadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Threads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Threads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Threads.
   */
  distinct?: Prisma.ThreadScalarFieldEnum | Prisma.ThreadScalarFieldEnum[]
}

/**
 * Thread findFirstOrThrow
 */
export type ThreadFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
  /**
   * Filter, which Thread to fetch.
   */
  where?: Prisma.ThreadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Threads to fetch.
   */
  orderBy?: Prisma.ThreadOrderByWithRelationInput | Prisma.ThreadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Threads.
   */
  cursor?: Prisma.ThreadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Threads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Threads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Threads.
   */
  distinct?: Prisma.ThreadScalarFieldEnum | Prisma.ThreadScalarFieldEnum[]
}

/**
 * Thread findMany
 */
export type ThreadFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
  /**
   * Filter, which Threads to fetch.
   */
  where?: Prisma.ThreadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Threads to fetch.
   */
  orderBy?: Prisma.ThreadOrderByWithRelationInput | Prisma.ThreadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Threads.
   */
  cursor?: Prisma.ThreadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Threads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Threads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Threads.
   */
  distinct?: Prisma.ThreadScalarFieldEnum | Prisma.ThreadScalarFieldEnum[]
}

/**
 * Thread create
 */
export type ThreadCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
  /**
   * The data needed to create a Thread.
   */
  data: Prisma.XOR<Prisma.ThreadCreateInput, Prisma.ThreadUncheckedCreateInput>
}

/**
 * Thread createMany
 */
export type ThreadCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Threads.
   */
  data: Prisma.ThreadCreateManyInput | Prisma.ThreadCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Thread createManyAndReturn
 */
export type ThreadCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * The data used to create many Threads.
   */
  data: Prisma.ThreadCreateManyInput | Prisma.ThreadCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Thread update
 */
export type ThreadUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
  /**
   * The data needed to update a Thread.
   */
  data: Prisma.XOR<Prisma.ThreadUpdateInput, Prisma.ThreadUncheckedUpdateInput>
  /**
   * Choose, which Thread to update.
   */
  where: Prisma.ThreadWhereUniqueInput
}

/**
 * Thread updateMany
 */
export type ThreadUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Threads.
   */
  data: Prisma.XOR<Prisma.ThreadUpdateManyMutationInput, Prisma.ThreadUncheckedUpdateManyInput>
  /**
   * Filter which Threads to update
   */
  where?: Prisma.ThreadWhereInput
  /**
   * Limit how many Threads to update.
   */
  limit?: number
}

/**
 * Thread updateManyAndReturn
 */
export type ThreadUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * The data used to update Threads.
   */
  data: Prisma.XOR<Prisma.ThreadUpdateManyMutationInput, Prisma.ThreadUncheckedUpdateManyInput>
  /**
   * Filter which Threads to update
   */
  where?: Prisma.ThreadWhereInput
  /**
   * Limit how many Threads to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Thread upsert
 */
export type ThreadUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
  /**
   * The filter to search for the Thread to update in case it exists.
   */
  where: Prisma.ThreadWhereUniqueInput
  /**
   * In case the Thread found by the `where` argument doesn't exist, create a new Thread with this data.
   */
  create: Prisma.XOR<Prisma.ThreadCreateInput, Prisma.ThreadUncheckedCreateInput>
  /**
   * In case the Thread was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ThreadUpdateInput, Prisma.ThreadUncheckedUpdateInput>
}

/**
 * Thread delete
 */
export type ThreadDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
  /**
   * Filter which Thread to delete.
   */
  where: Prisma.ThreadWhereUniqueInput
}

/**
 * Thread deleteMany
 */
export type ThreadDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Threads to delete
   */
  where?: Prisma.ThreadWhereInput
  /**
   * Limit how many Threads to delete.
   */
  limit?: number
}

/**
 * Thread.messages
 */
export type Thread$messagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  where?: Prisma.MessageWhereInput
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  cursor?: Prisma.MessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Thread without action
 */
export type ThreadDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Thread
   */
  select?: Prisma.ThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Thread
   */
  omit?: Prisma.ThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadInclude<ExtArgs> | null
}
