/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */
import type { ColumnType } from 'kysely';

export type AuthMethod = 'api_key' | 'app_password' | 'oauth2';

export type Channel = 'chat_room' | 'dm' | 'email' | 'sms';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Provider = 'generic_imap' | 'gmail' | 'icloud';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Attachment {
  contentType: string | null;
  createdAt: Generated<Timestamp>;
  filename: string;
  id: Generated<string>;
  messageId: string;
  orgId: string;
  sizeBytes: Int8 | null;
  storagePath: string;
}

export interface Contact {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isBlocked: Generated<boolean>;
  name: string | null;
  orgId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ContactHandle {
  channel: Channel;
  contactId: string;
  createdAt: Generated<Timestamp>;
  handle: string;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
}

export interface JobQueue {
  attempts: Generated<number>;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  dedupKey: string | null;
  id: Generated<string>;
  lastError: string | null;
  lockedAt: Timestamp | null;
  lockedBy: string | null;
  maxAttempts: Generated<number>;
  payload: Json;
  queue: Generated<string>;
  scheduledFor: Generated<Timestamp>;
  status: Generated<string>;
}

export interface Message {
  bccAddresses: Generated<string[] | null>;
  bodyHtml: string | null;
  bodyText: string | null;
  ccAddresses: Generated<string[] | null>;
  channel: Channel;
  createdAt: Generated<Timestamp>;
  direction: string;
  externalMessageId: string;
  id: Generated<string>;
  isArchived: Generated<boolean>;
  isDeleted: Generated<boolean>;
  isRead: Generated<boolean>;
  isStarred: Generated<boolean>;
  orgId: string;
  providerAccountId: string;
  receivedAt: Timestamp | null;
  recipientAddresses: Generated<string[]>;
  senderAddress: string;
  senderName: string | null;
  sentAt: Timestamp;
  subject: string | null;
  threadId: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface MessageRaw {
  contentType: string;
  createdAt: Generated<Timestamp>;
  messageId: string;
  payload: Json;
}

export interface Org {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  runOn: Timestamp;
}

export interface ProviderAccount {
  alias: string | null;
  authMethod: AuthMethod;
  channel: Channel;
  createdAt: Generated<Timestamp>;
  credentialsEncrypted: Buffer | null;
  externalAccountId: string;
  id: Generated<string>;
  isActive: Generated<boolean>;
  lastSyncedAt: Timestamp | null;
  orgId: string;
  provider: Provider;
  syncCursor: Json | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Thread {
  channel: Channel;
  createdAt: Generated<Timestamp>;
  externalThreadId: string | null;
  id: Generated<string>;
  lastMessageAt: Timestamp | null;
  messageCount: Generated<number>;
  orgId: string;
  subject: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string | null;
  orgId: string;
  role: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  attachment: Attachment;
  contact: Contact;
  contactHandle: ContactHandle;
  jobQueue: JobQueue;
  message: Message;
  messageRaw: MessageRaw;
  org: Org;
  pgmigrations: Pgmigrations;
  providerAccount: ProviderAccount;
  thread: Thread;
  user: User;
}
